/*	$OpenBSD$	*/
/*
 * Copyright (c) 2020 Fabien ROMANO <fabien@openbsd.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <string.h>
#include <bluetooth/bluetooth.h>

#ifndef nitems
#define nitems(_a) (sizeof((_a)) / sizeof((_a)[0]))
#endif

const char * const bt_error_strs[] = {
	"Success",
	"Unknown HCI Command",
	"Unknown Connection Identifier",
	"Hardware Failure",
	"Page Timeout",
	"Authentication Failure",
	"PIN or Key Missing",
	"Memory Capacity Exceeded",
	"Connection Timeout",
	"Connection Limit Exceeded",
	"Synchronous Connection Limit To A Device Exceeded",
	"Connection Already Exists",
	"Command Disallowed",
	"Connection Rejected due to Limited Resources",
	"Connection Rejected Due To Security Reasons",
	"Connection Rejected due to Unacceptable BD_ADDR",
	"Connection Accept Timeout Exceeded",
	"Unsupported Feature or Parameter Value",
	"Invalid HCI Command Parameters",
	"Remote User Terminated Connection",
	"Remote Device Terminated Connection due to Low Resources",
	"Remote Device Terminated Connection due to Power Off",
	"Connection Terminated By Local Host",
	"Repeated Attempts",
	"Pairing Not Allowed",
	"Unknown LMP PDU",
	"Unsupported Remote Feature / Unsupported LMP Feature",
	"SCO Offset Rejected",
	"SCO Interval Rejected",
	"SCO Air Mode Rejected",
	"Invalid LMP Parameters / Invalid LL Parameters",
	"Unspecified Error",
	"Unsupported LMP Parameter Value / Unsupported LL Parameter Value",
	"Role Change Not Allowed",
	"LMP Response Timeout / LL Response Timeout",
	"LMP Error Transaction Collision / LL Procedure Collision",
	"LMP PDU Not Allowed",
	"Encryption Mode Not Acceptable",
	"Link Key cannot be Changed",
	"Requested QoS Not Supported",
	"Instant Passed",
	"Pairing With Unit Key Not Supported",
	"Different Transaction Collision",
	"Reserved for future use",
	"QoS Unacceptable Parameter",
	"QoS Rejected",
	"Channel Classification Not Supported",
	"Insufficient Security",
	"Parameter Out Of Mandatory Range",
	"Reserved for future use",
	"Role Switch Pending",
	"Reserved for future use",
	"Reserved Slot Violation",
	"Role Switch Failed",
	"Extended Inquiry Response Too Large",
	"Secure Simple Pairing Not Supported By Host",
	"Host Busy - Pairing",
	"Connection Rejected due to No Suitable Channel Found",
	"Controller Busy",
	"Unacceptable Connection Parameters",
	"Advertising Timeout",
	"Connection Terminated due to MIC Failure",
	"Connection Failed to be Established / Synchronization Timeout",
	"MAC Connection Failed",
	"Coarse Clock Adjustment Rejected but Will Try to Adjust Using Clock",
	"Type0 Submap Not Defined",
	"Unknown Advertising Identifier",
	"Limit Reached",
	"Operation Cancelled by Host",
	"Packet Too Long",
};
const char *
btstrerror(int err)
{
	if (err < (1 << BT_ERR_SHIFT))
		return (strerror(err));
	err >>= BT_ERR_SHIFT;
	if (err >= nitems(bt_error_strs))
		return ("invalid error code");
	return (bt_error_strs[err]);
}

const char * const bt_hcimanufacturer_strs[] = {
	"Ericsson Technology Licensing",
	"Nokia Mobile Phones",
	"Intel Corp.",
	"IBM Corp.",
	"Toshiba Corp.",
	"3Com",
	"Microsoft",
	"Lucent",
	"Motorola",
	"Infineon Technologies AG",
	"Qualcomm Technologies International, Ltd. (QTIL)",
	"Silicon Wave",
	"Digianswer A/S",
	"Texas Instruments Inc.",
	"Parthus Technologies Inc.",
	"Broadcom Corporation",
	"Mitel Semiconductor",
	"Widcomm, Inc.",
	"Zeevo, Inc.",
	"Atmel Corporation",
	"Mitsubishi Electric Corporation",
	"RTX Telecom A/S",
	"KC Technology Inc.",
	"Newlogic",
	"Transilica, Inc.",
	"Rohde & Schwarz GmbH & Co. KG",
	"TTPCom Limited",
	"Signia Technologies, Inc.",
	"Conexant Systems Inc.",
	"Qualcomm",
	"Inventel",
	"AVM Berlin",
	"BandSpeed, Inc.",
	"Mansella Ltd",
	"NEC Corporation",
	"WavePlus Technology Co., Ltd.",
	"Alcatel",
	"NXP Semiconductors (formerly Philips Semiconductors)",
	"C Technologies",
	"Open Interface",
	"R F Micro Devices",
	"Hitachi Ltd",
	"Symbol Technologies, Inc.",
	"Tenovis",
	"Macronix International Co. Ltd.",
	"GCT Semiconductor",
	"Norwood Systems",
	"MewTel Technology Inc.",
	"ST Microelectronics",
	"Synopsys, Inc.",
	"Red-M (Communications) Ltd",
	"Commil Ltd",
	"Computer Access Technology Corporation (CATC)",
	"Eclipse (HQ Espana) S.L.",
	"Renesas Electronics Corporation",
	"Mobilian Corporation",
	"Syntronix Corporation",
	"Integrated System Solution Corp.",
	"Panasonic Corporation (formerly Matsushita Electric Industrial Co., Ltd.)",
	"Gennum Corporation",
	"BlackBerry Limited (formerly Research In Motion)",
	"IPextreme, Inc.",
	"Systems and Chips, Inc",
	"Bluetooth SIG, Inc",
	"Seiko Epson Corporation",
	"Integrated Silicon Solution Taiwan, Inc.",
	"CONWISE Technology Corporation Ltd",
	"PARROT AUTOMOTIVE SAS",
	"Socket Mobile",
	"Atheros Communications, Inc.",
	"MediaTek, Inc.",
	"Bluegiga",
	"Marvell Technology Group Ltd.",
	"3DSP Corporation",
	"Accel Semiconductor Ltd.",
	"Continental Automotive Systems",
	"Apple, Inc.",
	"Staccato Communications, Inc.",
	"Avago Technologies",
	"APT Ltd.",
	"SiRF Technology, Inc.",
	"Tzero Technologies, Inc.",
	"J&M Corporation",
	"Free2move AB",
	"3DiJoy Corporation",
	"Plantronics, Inc.",
	"Sony Ericsson Mobile Communications",
	"Harman International Industries, Inc.",
	"Vizio, Inc.",
	"Nordic Semiconductor ASA",
	"EM Microelectronic-Marin SA",
	"Ralink Technology Corporation",
	"Belkin International, Inc.",
	"Realtek Semiconductor Corporation",
	"Stonestreet One, LLC",
	"Wicentric, Inc.",
	"RivieraWaves S.A.S",
	"RDA Microelectronics",
	"Gibson Guitars",
	"MiCommand Inc.",
	"Band XI International, LLC",
	"Hewlett-Packard Company",
	"9Solutions Oy",
	"GN Netcom A/S",
	"General Motors",
	"A&D Engineering, Inc.",
	"MindTree Ltd.",
	"Polar Electro OY",
	"Beautiful Enterprise Co., Ltd.",
	"BriarTek, Inc",
	"Summit Data Communications, Inc.",
	"Sound ID",
	"Monster, LLC",
	"connectBlue AB",
	"ShangHai Super Smart Electronics Co. Ltd.",
	"Group Sense Ltd.",
	"Zomm, LLC",
	"Samsung Electronics Co. Ltd.",
	"Creative Technology Ltd.",
	"Laird Technologies",
	"Nike, Inc.",
	"lesswire AG",
	"MStar Semiconductor, Inc.",
	"Hanlynn Technologies",
	"A & R Cambridge",
	"Seers Technology Co., Ltd.",
	"Sports Tracking Technologies Ltd.",
	"Autonet Mobile",
	"DeLorme Publishing Company, Inc.",
	"WuXi Vimicro",
	"Sennheiser Communications A/S",
	"TimeKeeping Systems, Inc.",
	"Ludus Helsinki Ltd.",
	"BlueRadios, Inc.",
	"Equinux AG",
	"Garmin International, Inc.",
	"Ecotest",
	"GN ReSound A/S",
	"Jawbone",
	"Topcon Positioning Systems, LLC",
	"Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)",
	"Zscan Software",
	"Quintic Corp",
	"Telit Wireless Solutions GmbH (formerly Stollmann E+V GmbH)",
	"Funai Electric Co., Ltd.",
	"Advanced PANMOBIL systems GmbH & Co. KG",
	"ThinkOptics, Inc.",
	"Universal Electronics, Inc.",
	"Airoha Technology Corp.",
	"NEC Lighting, Ltd.",
	"ODM Technology, Inc.",
	"ConnecteDevice Ltd.",
	"zero1.tv GmbH",
	"i.Tech Dynamic Global Distribution Ltd.",
	"Alpwise",
	"Jiangsu Toppower Automotive Electronics Co., Ltd.",
	"Colorfy, Inc.",
	"Geoforce Inc.",
	"Bose Corporation",
	"Suunto Oy",
	"Kensington Computer Products Group",
	"SR-Medizinelektronik",
	"Vertu Corporation Limited",
	"Meta Watch Ltd.",
	"LINAK A/S",
	"OTL Dynamics LLC",
	"Panda Ocean Inc.",
	"Visteon Corporation",
	"ARP Devices Limited",
	"MARELLI EUROPE S.P.A. (formerly Magneti Marelli S.p.A.)",
	"CAEN RFID srl",
	"Ingenieur-Systemgruppe Zahn GmbH",
	"Green Throttle Games",
	"Peter Systemtechnik GmbH",
	"Omegawave Oy",
	"Cinetix",
	"Passif Semiconductor Corp",
	"Saris Cycling Group, Inc",
	"​Bekey A/S",
	"​Clarinox Technologies Pty. Ltd.",
	"​BDE Technology Co., Ltd.",
	"Swirl Networks",
	"​Meso international",
	"​TreLab Ltd",
	"​Qualcomm Innovation Center, Inc. (QuIC)",
	"​​Johnson Controls, Inc.",
	"​Starkey Laboratories Inc.",
	"​​S-Power Electronics Limited",
	"​​Ace Sensor Inc",
	"​​Aplix Corporation",
	"​​AAMP of America",
	"​​Stalmart Technology Limited",
	"​​AMICCOM Electronics Corporation",
	"​​Shenzhen Excelsecu Data Technology Co.,Ltd",
	"​​Geneq Inc.",
	"​​adidas AG",
	"​​LG Electronics​",
	"​Onset Computer Corporation",
	"​Selfly BV",
	"​Quuppa Oy.",
	"GeLo Inc",
	"Evluma",
	"MC10",
	"Binauric SE",
	"Beats Electronics",
	"Microchip Technology Inc.",
	"Elgato Systems GmbH",
	"ARCHOS SA",
	"Dexcom, Inc.",
	"Polar Electro Europe B.V.",
	"Dialog Semiconductor B.V.",
	"Taixingbang Technology (HK) Co,. LTD.",
	"Kawantech",
	"Austco Communication Systems",
	"Timex Group USA, Inc.",
	"Qualcomm Technologies, Inc.",
	"Qualcomm Connected Experiences, Inc.",
	"Voyetra Turtle Beach",
	"txtr GmbH",
	"Biosentronics",
	"Procter & Gamble",
	"Hosiden Corporation",
	"Muzik LLC",
	"Misfit Wearables Corp",
	"Google",
	"Danlers Ltd",
	"Semilink Inc",
	"inMusic Brands, Inc",
	"L.S. Research Inc.",
	"Eden Software Consultants Ltd.",
	"Freshtemp",
	"​KS Technologies",
	"​ACTS Technologies",
	"​Vtrack Systems",
	"​Nielsen-Kellerman Company",
	"Server Technology Inc.",
	"BioResearch Associates",
	"Jolly Logic, LLC",
	"Above Average Outcomes, Inc.",
	"Bitsplitters GmbH",
	"PayPal, Inc.",
	"Witron Technology Limited",
	"Morse Project Inc.",
	"Kent Displays Inc.",
	"Nautilus Inc.",
	"Smartifier Oy",
	"Elcometer Limited",
	"VSN Technologies, Inc.",
	"AceUni Corp., Ltd.",
	"StickNFind",
	"Crystal Code AB",
	"KOUKAAM a.s.",
	"Delphi Corporation",
	"ValenceTech Limited",
	"Stanley Black and Decker",
	"Typo Products, LLC",
	"TomTom International BV",
	"Fugoo, Inc.",
	"Keiser Corporation",
	"Bang & Olufsen A/S",
	"PLUS Location Systems Pty Ltd",
	"Ubiquitous Computing Technology Corporation",
	"Innovative Yachtter Solutions",
	"William Demant Holding A/S",
	"Chicony Electronics Co., Ltd.",
	"Atus BV",
	"Codegate Ltd",
	"ERi, Inc",
	"Transducers Direct, LLC",
	"DENSO TEN LIMITED (formerly Fujitsu Ten LImited)",
	"Audi AG",
	"HiSilicon Technologies CO., LIMITED",
	"Nippon Seiki Co., Ltd.",
	"Steelseries ApS",
	"Visybl Inc.",
	"Openbrain Technologies, Co., Ltd.",
	"Xensr",
	"e.solutions",
	"10AK Technologies",
	"Wimoto Technologies Inc",
	"Radius Networks, Inc.",
	"Wize Technology Co., Ltd.",
	"Qualcomm Labs, Inc.",
	"Hewlett Packard Enterprise",
	"Baidu",
	"Arendi AG",
	"Skoda Auto a.s.",
	"Volkswagen AG",
	"Porsche AG",
	"Sino Wealth Electronic Ltd.",
	"AirTurn, Inc.",
	"Kinsa, Inc",
	"HID Global",
	"SEAT es",
	"Promethean Ltd.",
	"Salutica Allied Solutions",
	"GPSI Group Pty Ltd",
	"Nimble Devices Oy",
	"Changzhou Yongse Infotech Co., Ltd.",
	"SportIQ",
	"TEMEC Instruments B.V.",
	"Sony Corporation",
	"ASSA ABLOY",
	"Clarion Co. Inc.",
	"Warehouse Innovations",
	"Cypress Semiconductor",
	"MADS Inc",
	"Blue Maestro Limited",
	"Resolution Products, Ltd.",
	"Aireware LLC",
	"Silvair, Inc.",
	"Prestigio Plaza Ltd.",
	"NTEO Inc.",
	"Focus Systems Corporation",
	"Tencent Holdings Ltd.",
	"Allegion",
	"Murata Manufacturing Co., Ltd.",
	"WirelessWERX",
	"Nod, Inc.",
	"B&B Manufacturing Company",
	"Alpine Electronics (China) Co., Ltd",
	"FedEx Services",
	"Grape Systems Inc.",
	"Bkon Connect",
	"Lintech GmbH",
	"Novatel Wireless",
	"Ciright",
	"Mighty Cast, Inc.",
	"Ambimat Electronics",
	"Perytons Ltd.",
	"Tivoli Audio, LLC",
	"Master Lock",
	"Mesh-Net Ltd",
	"HUIZHOU DESAY SV AUTOMOTIVE CO., LTD.",
	"Tangerine, Inc.",
	"B&W Group Ltd.",
	"Pioneer Corporation",
	"OnBeep",
	"Vernier Software & Technology",
	"ROL Ergo",
	"Pebble Technology",
	"NETATMO",
	"Accumulate AB",
	"Anhui Huami Information Technology Co., Ltd.",
	"Inmite s.r.o.",
	"ChefSteps, Inc.",
	"micas AG",
	"Biomedical Research Ltd.",
	"Pitius Tec S.L.",
	"Estimote, Inc.",
	"Unikey Technologies, Inc.",
	"Timer Cap Co.",
	"AwoX",
	"yikes",
	"MADSGlobalNZ Ltd.",
	"PCH International",
	"Qingdao Yeelink Information Technology Co., Ltd.",
	"Milwaukee Tool (Formally Milwaukee Electric Tools)",
	"MISHIK Pte Ltd",
	"Ascensia Diabetes Care US Inc.",
	"Spicebox LLC",
	"emberlight",
	"Cooper-Atkins Corporation",
	"Qblinks",
	"MYSPHERA",
	"LifeScan Inc",
	"Volantic AB",
	"Podo Labs, Inc",
	"Roche Diabetes Care AG",
	"Amazon Fulfillment Service",
	"Connovate Technology Private Limited",
	"Kocomojo, LLC",
	"Everykey Inc.",
	"Dynamic Controls",
	"SentriLock",
	"I-SYST inc.",
	"CASIO COMPUTER CO., LTD.",
	"LAPIS Semiconductor Co., Ltd.",
	"Telemonitor, Inc.",
	"taskit GmbH",
	"Daimler AG",
	"BatAndCat",
	"BluDotz Ltd",
	"XTel Wireless ApS",
	"Gigaset Communications GmbH",
	"Gecko Health Innovations, Inc.",
	"HOP Ubiquitous",
	"Walt Disney",
	"Nectar",
	"bel'apps LLC",
	"CORE Lighting Ltd",
	"Seraphim Sense Ltd",
	"Unico RBC",
	"Physical Enterprises Inc.",
	"Able Trend Technology Limited",
	"Konica Minolta, Inc.",
	"Wilo SE",
	"Extron Design Services",
	"Fitbit, Inc.",
	"Fireflies Systems",
	"Intelletto Technologies Inc.",
	"FDK CORPORATION",
	"Cloudleaf, Inc",
	"Maveric Automation LLC",
	"Acoustic Stream Corporation",
	"Zuli",
	"Paxton Access Ltd",
	"WiSilica Inc.",
	"VENGIT Korlatolt Felelossegu Tarsasag",
	"SALTO SYSTEMS S.L.",
	"TRON Forum (formerly T-Engine Forum)",
	"CUBETECH s.r.o.",
	"Cokiya Incorporated",
	"CVS Health",
	"Ceruus",
	"Strainstall Ltd",
	"Channel Enterprises (HK) Ltd.",
	"FIAMM",
	"GIGALANE.CO.,LTD",
	"EROAD",
	"Mine Safety Appliances",
	"Icon Health and Fitness",
	"Wille Engineering (formely as Asandoo GmbH)",
	"ENERGOUS CORPORATION",
	"Taobao",
	"Canon Inc.",
	"Geophysical Technology Inc.",
	"Facebook, Inc.",
	"Trividia Health, Inc.",
	"FlightSafety International",
	"Earlens Corporation",
	"Sunrise Micro Devices, Inc.",
	"Star Micronics Co., Ltd.",
	"Netizens Sp. z o.o.",
	"Nymi Inc.",
	"Nytec, Inc.",
	"Trineo Sp. z o.o.",
	"Nest Labs Inc.",
	"LM Technologies Ltd",
	"General Electric Company",
	"i+D3 S.L.",
	"HANA Micron",
	"Stages Cycling LLC",
	"Cochlear Bone Anchored Solutions AB",
	"SenionLab AB",
	"Syszone Co., Ltd",
	"Pulsate Mobile Ltd.",
	"Hong Kong HunterSun Electronic Limited",
	"pironex GmbH",
	"BRADATECH Corp.",
	"Transenergooil AG",
	"Bunch",
	"DME Microelectronics",
	"Bitcraze AB",
	"HASWARE Inc.",
	"Abiogenix Inc.",
	"Poly-Control ApS",
	"Avi-on",
	"Laerdal Medical AS",
	"Fetch My Pet",
	"Sam Labs Ltd.",
	"Chengdu Synwing Technology Ltd",
	"HOUWA SYSTEM DESIGN, k.k.",
	"BSH",
	"Primus Inter Pares Ltd",
	"August Home, Inc",
	"Gill Electronics",
	"Sky Wave Design",
	"Newlab S.r.l.",
	"ELAD srl",
	"G-wearables inc.",
	"Squadrone Systems Inc.",
	"Code Corporation",
	"Savant Systems LLC",
	"Logitech International SA",
	"Innblue Consulting",
	"iParking Ltd.",
	"Koninklijke Philips Electronics N.V.",
	"Minelab Electronics Pty Limited",
	"Bison Group Ltd.",
	"Widex A/S",
	"Jolla Ltd",
	"Lectronix, Inc.",
	"Caterpillar Inc",
	"Freedom Innovations",
	"Dynamic Devices Ltd",
	"Technology Solutions (UK) Ltd",
	"IPS Group Inc.",
	"STIR",
	"Sano, Inc.",
	"Advanced Application Design, Inc.",
	"AutoMap LLC",
	"Spreadtrum Communications Shanghai Ltd",
	"CuteCircuit LTD",
	"Valeo Service",
	"Fullpower Technologies, Inc.",
	"KloudNation",
	"Zebra Technologies Corporation",
	"Itron, Inc.",
	"The University of Tokyo",
	"UTC Fire and Security",
	"Cool Webthings Limited",
	"DJO Global",
	"Gelliner Limited",
	"Anyka (Guangzhou) Microelectronics Technology Co, LTD",
	"Medtronic Inc.",
	"Gozio Inc.",
	"Form Lifting, LLC",
	"Wahoo Fitness, LLC",
	"Kontakt Micro-Location Sp. z o.o.",
	"Radio Systems Corporation",
	"Freescale Semiconductor, Inc.",
	"Verifone Systems Pte Ltd. Taiwan Branch",
	"AR Timing",
	"Rigado LLC",
	"Kemppi Oy",
	"Tapcentive Inc.",
	"Smartbotics Inc.",
	"Otter Products, LLC",
	"STEMP Inc.",
	"LumiGeek LLC",
	"InvisionHeart Inc.",
	"Macnica Inc.",
	"Jaguar Land Rover Limited",
	"CoroWare Technologies, Inc",
	"Simplo Technology Co., LTD",
	"Omron Healthcare Co., LTD",
	"Comodule GMBH",
	"ikeGPS",
	"Telink Semiconductor Co. Ltd",
	"Interplan Co., Ltd",
	"Wyler AG",
	"IK Multimedia Production srl",
	"Lukoton Experience Oy",
	"MTI Ltd",
	"Tech4home, Lda",
	"Hiotech AB",
	"DOTT Limited",
	"Blue Speck Labs, LLC",
	"Cisco Systems, Inc",
	"Mobicomm Inc",
	"Edamic",
	"Goodnet, Ltd",
	"Luster Leaf Products Inc",
	"Manus Machina BV",
	"Mobiquity Networks Inc",
	"Praxis Dynamics",
	"Philip Morris Products S.A.",
	"Comarch SA",
	"Nestlé Nespresso S.A.",
	"Merlinia A/S",
	"LifeBEAM Technologies",
	"Twocanoes Labs, LLC",
	"Muoverti Limited",
	"Stamer Musikanlagen GMBH",
	"Tesla Motors",
	"Pharynks Corporation",
	"Lupine",
	"Siemens AG",
	"Huami (Shanghai) Culture Communication CO., LTD",
	"Foster Electric Company, Ltd",
	"ETA SA",
	"x-Senso Solutions Kft",
	"Shenzhen SuLong Communication Ltd",
	"FengFan (BeiJing) Technology Co, Ltd",
	"Qrio Inc",
	"Pitpatpet Ltd",
	"MSHeli s.r.l.",
	"Trakm8 Ltd",
	"JIN CO, Ltd",
	"Alatech Tehnology",
	"Beijing CarePulse Electronic Technology Co, Ltd",
	"Awarepoint",
	"ViCentra B.V.",
	"Raven Industries",
	"WaveWare Technologies Inc.",
	"Argenox Technologies",
	"Bragi GmbH",
	"16Lab Inc",
	"Masimo Corp",
	"Iotera Inc",
	"Endress+Hauser ",
	"ACKme Networks, Inc.",
	"FiftyThree Inc.",
	"Parker Hannifin Corp",
	"Transcranial Ltd",
	"Uwatec AG",
	"Orlan LLC",
	"Blue Clover Devices",
	"M-Way Solutions GmbH",
	"Microtronics Engineering GmbH",
	"Schneider Schreibgeräte GmbH",
	"Sapphire Circuits LLC",
	"Lumo Bodytech Inc.",
	"UKC Technosolution",
	"Xicato Inc.",
	"Playbrush",
	"Dai Nippon Printing Co., Ltd.",
	"G24 Power Limited",
	"AdBabble Local Commerce Inc.",
	"Devialet SA",
	"ALTYOR",
	"University of Applied Sciences Valais/Haute Ecole Valaisanne",
	"Five Interactive, LLC dba Zendo",
	"NetEase（Hangzhou）Network co.Ltd.",
	"Lexmark International Inc.",
	"Fluke Corporation",
	"Yardarm Technologies",
	"SensaRx",
	"SECVRE GmbH",
	"Glacial Ridge Technologies",
	"Identiv, Inc.",
	"DDS, Inc.",
	"SMK Corporation",
	"Schawbel Technologies LLC",
	"XMI Systems SA",
	"Cerevo",
	"Torrox GmbH & Co KG",
	"Gemalto",
	"DEKA Research & Development Corp.",
	"Domster Tadeusz Szydlowski",
	"Technogym SPA",
	"FLEURBAEY BVBA",
	"Aptcode Solutions",
	"LSI ADL Technology",
	"Animas Corp",
	"Alps Electric Co., Ltd.",
	"OCEASOFT",
	"Motsai Research",
	"Geotab",
	"E.G.O. Elektro-Geraetebau GmbH",
	"bewhere inc",
	"Johnson Outdoors Inc",
	"steute Schaltgerate GmbH & Co. KG",
	"Ekomini inc.",
	"DEFA AS",
	"Aseptika Ltd",
	"HUAWEI Technologies Co., Ltd.",
	"HabitAware, LLC",
	"ruwido austria gmbh",
	"ITEC corporation",
	"StoneL",
	"Sonova AG",
	"Maven Machines, Inc.",
	"Synapse Electronics",
	"Standard Innovation Inc.",
	"RF Code, Inc.",
	"Wally Ventures S.L.",
	"Willowbank Electronics Ltd",
	"SK Telecom",
	"Jetro AS",
	"Code Gears LTD",
	"NANOLINK APS",
	"IF, LLC",
	"RF Digital Corp",
	"Church & Dwight Co., Inc",
	"Multibit Oy",
	"CliniCloud Inc",
	"SwiftSensors",
	"Blue Bite",
	"ELIAS GmbH",
	"Sivantos GmbH",
	"Petzl",
	"storm power ltd",
	"EISST Ltd",
	"Inexess Technology Simma KG",
	"Currant, Inc.",
	"C2 Development, Inc.",
	"Blue Sky Scientific, LLC",
	"ALOTTAZS LABS, LLC",
	"Kupson spol. s r.o.",
	"Areus Engineering GmbH",
	"Impossible Camera GmbH",
	"InventureTrack Systems",
	"LockedUp",
	"Itude",
	"Pacific Lock Company",
	"Tendyron Corporation ( 天地融科技股份有限公司 )",
	"Robert Bosch GmbH",
	"Illuxtron international B.V.",
	"miSport Ltd.",
	"Chargelib",
	"Doppler Lab",
	"BBPOS Limited",
	"RTB Elektronik GmbH & Co. KG",
	"Rx Networks, Inc.",
	"WeatherFlow, Inc.",
	"Technicolor USA Inc.",
	"Bestechnic(Shanghai),Ltd",
	"Raden Inc",
	"JouZen Oy",
	"CLABER S.P.A.",
	"Hyginex, Inc.",
	"HANSHIN ELECTRIC RAILWAY CO.,LTD.",
	"Schneider Electric",
	"Oort Technologies LLC",
	"Chrono Therapeutics",
	"Rinnai Corporation",
	"Swissprime Technologies AG",
	"Koha.,Co.Ltd",
	"Genevac Ltd",
	"Chemtronics",
	"Seguro Technology Sp. z o.o.",
	"Redbird Flight Simulations",
	"Dash Robotics",
	"LINE Corporation",
	"Guillemot Corporation",
	"Techtronic Power Tools Technology Limited",
	"Wilson Sporting Goods",
	"Lenovo (Singapore) Pte Ltd. ( 联想（新加坡） )",
	"Ayatan Sensors",
	"Electronics Tomorrow Limited",
	"VASCO Data Security International, Inc.",
	"PayRange Inc.",
	"ABOV Semiconductor",
	"AINA-Wireless Inc.",
	"Eijkelkamp Soil & Water",
	"BMA ergonomics b.v.",
	"Teva Branded Pharmaceutical Products R&D, Inc.",
	"Anima",
	"3M",
	"Empatica Srl",
	"Afero, Inc.",
	"Powercast Corporation",
	"Secuyou ApS",
	"OMRON Corporation",
	"Send Solutions",
	"NIPPON SYSTEMWARE CO.,LTD.",
	"Neosfar",
	"Fliegl Agrartechnik GmbH",
	"Gilvader",
	"Digi International Inc (R)",
	"DeWalch Technologies, Inc.",
	"Flint Rehabilitation Devices, LLC",
	"Samsung SDS Co., Ltd.",
	"Blur Product Development",
	"University of Michigan",
	"Victron Energy BV",
	"NTT docomo",
	"Carmanah Technologies Corp.",
	"Bytestorm Ltd.",
	"Espressif Incorporated ( 乐鑫信息科技(上海)有限公司 )",
	"Unwire",
	"Connected Yard, Inc.",
	"American Music Environments",
	"Sensogram Technologies, Inc.",
	"Fujitsu Limited",
	"Ardic Technology",
	"Delta Systems, Inc",
	"HTC Corporation ",
	"Citizen Holdings Co., Ltd. ",
	"SMART-INNOVATION.inc",
	"Blackrat Software ",
	"The Idea Cave, LLC",
	"GoPro, Inc.",
	"AuthAir, Inc",
	"Vensi, Inc.",
	"Indagem Tech LLC",
	"Intemo Technologies",
	"DreamVisions co., Ltd.",
	"Runteq Oy Ltd",
	"IMAGINATION TECHNOLOGIES LTD ",
	"CoSTAR TEchnologies",
	"Clarius Mobile Health Corp.",
	"Shanghai Frequen Microelectronics Co., Ltd.",
	"Uwanna, Inc.",
	"Lierda Science & Technology Group Co., Ltd.",
	"Silicon Laboratories",
	"World Moto Inc.",
	"Giatec Scientific Inc.",
	"Loop Devices, Inc",
	"IACA electronique",
	"Proxy Technologies, Inc.",
	"Swipp ApS",
	"Life Laboratory Inc. ",
	"FUJI INDUSTRIAL CO.,LTD.",
	"Surefire, LLC",
	"Dolby Labs",
	"Ellisys",
	"Magnitude Lighting Converters",
	"Hilti AG",
	"Devdata S.r.l.",
	"Deviceworx",
	"Shortcut Labs",
	"SGL Italia S.r.l.",
	"PEEQ DATA",
	"Ducere Technologies Pvt Ltd ",
	"DiveNav, Inc. ",
	"RIIG AI Sp. z o.o.",
	"Thermo Fisher Scientific ",
	"AG Measurematics Pvt. Ltd. ",
	"CHUO Electronics CO., LTD. ",
	"Aspenta International ",
	"Eugster Frismag AG ",
	"Amber wireless GmbH ",
	"HQ Inc ",
	"Lab Sensor Solutions ",
	"Enterlab ApS ",
	"Eyefi, Inc.",
	"MetaSystem S.p.A. ",
	"SONO ELECTRONICS. CO., LTD ",
	"Jewelbots ",
	"Compumedics Limited ",
	"Rotor Bike Components ",
	"Astro, Inc. ",
	"Amotus Solutions ",
	"Healthwear Technologies (Changzhou)Ltd ",
	"Essex Electronics ",
	"Grundfos A/S",
	"Eargo, Inc. ",
	"Electronic Design Lab ",
	"ESYLUX ",
	"NIPPON SMT.CO.,Ltd",
	"BM innovations GmbH ",
	"indoormap",
	"OttoQ Inc ",
	"North Pole Engineering ",
	"3flares Technologies Inc.",
	"Electrocompaniet A.S. ",
	"Mul-T-Lock",
	"Corentium AS ",
	"Enlighted Inc",
	"GISTIC",
	"AJP2 Holdings, LLC",
	"COBI GmbH ",
	"Blue Sky Scientific, LLC ",
	"Appception, Inc.",
	"Courtney Thorne Limited ",
	"Virtuosys",
	"TPV Technology Limited ",
	"Monitra SA",
	"Automation Components, Inc. ",
	"Letsense s.r.l. ",
	"Etesian Technologies LLC ",
	"GERTEC BRASIL LTDA. ",
	"Drekker Development Pty. Ltd.",
	"Whirl Inc ",
	"Locus Positioning ",
	"Acuity Brands Lighting, Inc ",
	"Prevent Biometrics ",
	"Arioneo",
	"VersaMe ",
	"Vaddio ",
	"Libratone A/S ",
	"HM Electronics, Inc. ",
	"TASER International, Inc.",
	"SafeTrust Inc. ",
	"Heartland Payment Systems ",
	"Bitstrata Systems Inc. ",
	"Pieps GmbH ",
	"iRiding(Xiamen)Technology Co.,Ltd.",
	"Alpha Audiotronics, Inc. ",
	"TOPPAN FORMS CO.,LTD. ",
	"Sigma Designs, Inc. ",
	"Spectrum Brands, Inc. ",
	"Polymap Wireless ",
	"MagniWare Ltd.",
	"Novotec Medical GmbH ",
	"Medicom Innovation Partner a/s ",
	"Matrix Inc. ",
	"Eaton Corporation ",
	"KYS",
	"Naya Health, Inc. ",
	"Acromag ",
	"Insulet Corporation ",
	"Wellinks Inc. ",
	"ON Semiconductor",
	"FREELAP SA ",
	"Favero Electronics Srl ",
	"BioMech Sensor LLC ",
	"BOLTT Sports technologies Private limited",
	"Saphe International ",
	"Metormote AB ",
	"littleBits ",
	"SetPoint Medical ",
	"BRControls Products BV ",
	"Zipcar ",
	"AirBolt Pty Ltd ",
	"KeepTruckin Inc ",
	"Motiv, Inc. ",
	"Wazombi Labs OÜ ",
	"ORBCOMM",
	"Nixie Labs, Inc.",
	"AppNearMe Ltd",
	"Holman Industries",
	"Expain AS",
	"Electronic Temperature Instruments Ltd",
	"Plejd AB",
	"Propeller Health",
	"Shenzhen iMCO Electronic Technology Co.,Ltd",
	"Algoria",
	"Apption Labs Inc.",
	"Cronologics Corporation",
	"MICRODIA Ltd.",
	"lulabytes S.L.",
	"Société des Produits Nestlé S.A. (formerly Nestec S.A.)",
	"LLC \"MEGA-F service\"",
	"Sharp Corporation",
	"Precision Outcomes Ltd",
	"Kronos Incorporated",
	"OCOSMOS Co., Ltd.",
	"Embedded Electronic Solutions Ltd. dba e2Solutions",
	"Aterica Inc.",
	"BluStor PMC, Inc.",
	"Kapsch TrafficCom AB",
	"ActiveBlu Corporation",
	"Kohler Mira Limited",
	"Noke",
	"Appion Inc.",
	"Resmed Ltd",
	"Crownstone B.V.",
	"Xiaomi Inc.",
	"INFOTECH s.r.o.",
	"Thingsquare AB",
	"T&D",
	"LAVAZZA S.p.A.",
	"Netclearance Systems, Inc.",
	"SDATAWAY",
	"BLOKS GmbH",
	"LEGO System A/S",
	"Thetatronics Ltd",
	"Nikon Corporation",
	"NeST",
	"South Silicon Valley Microelectronics",
	"ALE International",
	"CareView Communications, Inc.",
	"SchoolBoard Limited",
	"Molex Corporation",
	"IVT Wireless Limited",
	"Alpine Labs LLC",
	"Candura Instruments",
	"SmartMovt Technology Co., Ltd",
	"Token Zero Ltd",
	"ACE CAD Enterprise Co., Ltd. (ACECAD)",
	"Medela, Inc",
	"AeroScout",
	"Esrille Inc.",
	"THINKERLY SRL",
	"Exon Sp. z o.o.",
	"Meizu Technology Co., Ltd.",
	"Smablo LTD",
	"XiQ",
	"Allswell Inc.",
	"Comm-N-Sense Corp DBA Verigo",
	"VIBRADORM GmbH",
	"Otodata Wireless Network Inc.",
	"Propagation Systems Limited",
	"Midwest Instruments & Controls",
	"Alpha Nodus, inc.",
	"petPOMM, Inc",
	"Mattel",
	"Airbly Inc.",
	"A-Safe Limited",
	"FREDERIQUE CONSTANT SA",
	"Maxscend Microelectronics Company Limited",
	"Abbott",
	"ASB Bank Ltd",
	"amadas",
	"Applied Science, Inc.",
	"iLumi Solutions Inc.",
	"Arch Systems Inc.",
	"Ember Technologies, Inc.",
	"Snapchat Inc",
	"Casambi Technologies Oy",
	"Pico Technology Inc.",
	"St. Jude Medical, Inc.",
	"Intricon",
	"Structural Health Systems, Inc.",
	"Avvel International",
	"Gallagher Group",
	"In2things Automation Pvt. Ltd.",
	"SYSDEV Srl",
	"Vonkil Technologies Ltd",
	"Wynd Technologies, Inc.",
	"CONTRINEX S.A.",
	"MIRA, Inc.",
	"Watteam Ltd",
	"Density Inc.",
	"IOT Pot India Private Limited",
	"Sigma Connectivity AB",
	"PEG PEREGO SPA",
	"Wyzelink Systems Inc.",
	"Yota Devices LTD",
	"FINSECUR",
	"Zen-Me Labs Ltd",
	"3IWare Co., Ltd.",
	"EnOcean GmbH",
	"Instabeat, Inc",
	"Nima Labs",
	"Andreas Stihl AG & Co. KG",
	"Nathan Rhoades LLC",
	"Grob Technologies, LLC",
	"Actions (Zhuhai) Technology Co., Limited",
	"SPD Development Company Ltd",
	"Sensoan Oy",
	"Qualcomm Life Inc",
	"Chip-ing AG",
	"ffly4u",
	"IoT Instruments Oy",
	"TRUE Fitness Technology",
	"Reiner Kartengeraete GmbH & Co. KG.",
	"SHENZHEN LEMONJOY TECHNOLOGY CO., LTD.",
	"Hello Inc.",
	"Evollve Inc.",
	"Jigowatts Inc.",
	"BASIC MICRO.COM,INC.",
	"CUBE TECHNOLOGIES",
	"foolography GmbH",
	"CLINK",
	"Hestan Smart Cooking Inc.",
	"WindowMaster A/S",
	"Flowscape AB",
	"PAL Technologies Ltd",
	"WHERE, Inc.",
	"Iton Technology Corp.",
	"Owl Labs Inc.",
	"Rockford Corp.",
	"Becon Technologies Co.,Ltd.",
	"Vyassoft Technologies Inc",
	"Nox Medical",
	"Kimberly-Clark",
	"Trimble Navigation Ltd.",
	"Littelfuse",
	"Withings",
	"i-developer IT Beratung UG",
	"Relations Inc.",
	"Sears Holdings Corporation",
	"Gantner Electronic GmbH",
	"Authomate Inc",
	"Vertex International, Inc.",
	"Airtago",
	"Swiss Audio SA",
	"ToGetHome Inc.",
	"AXIS",
	"Openmatics",
	"Jana Care Inc.",
	"Senix Corporation",
	"NorthStar Battery Company, LLC",
	"SKF (U.K.) Limited",
	"CO-AX Technology, Inc.",
	"Fender Musical Instruments",
	"Luidia Inc",
	"SEFAM",
	"Wireless Cables Inc",
	"Lightning Protection International Pty Ltd",
	"Uber Technologies Inc",
	"SODA GmbH",
	"Fatigue Science",
	"Alpine Electronics Inc.",
	"Novalogy LTD",
	"Friday Labs Limited",
	"OrthoAccel Technologies",
	"WaterGuru, Inc.",
	"Benning Elektrotechnik und Elektronik GmbH & Co. KG",
	"Dell Computer Corporation",
	"Kopin Corporation",
	"TecBakery GmbH",
	"Backbone Labs, Inc.",
	"DELSEY SA",
	"Chargifi Limited",
	"Trainesense Ltd.",
	"Unify Software and Solutions GmbH & Co. KG",
	"Husqvarna AB",
	"Focus fleet and fuel management inc",
	"SmallLoop, LLC",
	"Prolon Inc.",
	"BD Medical",
	"iMicroMed Incorporated",
	"Ticto N.V.",
	"Meshtech AS",
	"MemCachier Inc.",
	"Danfoss A/S",
	"SnapStyk Inc.",
	"Amway Corporation",
	"Silk Labs, Inc.",
	"Pillsy Inc.",
	"Hatch Baby, Inc.",
	"Blocks Wearables Ltd.",
	"Drayson Technologies (Europe) Limited",
	"eBest IOT Inc.",
	"Helvar Ltd",
	"Radiance Technologies",
	"Nuheara Limited",
	"Appside co., ltd.",
	"DeLaval",
	"Coiler Corporation",
	"Thermomedics, Inc.",
	"Tentacle Sync GmbH",
	"Valencell, Inc.",
	"iProtoXi Oy",
	"SECOM CO., LTD.",
	"Tucker International LLC",
	"Metanate Limited",
	"Kobian Canada Inc.",
	"NETGEAR, Inc.",
	"Fabtronics Australia Pty Ltd",
	"Grand Centrix GmbH",
	"1UP USA.com llc",
	"SHIMANO INC.",
	"Nain Inc.",
	"LifeStyle Lock, LLC",
	"VEGA Grieshaber KG",
	"Xtrava Inc.",
	"TTS Tooltechnic Systems AG & Co. KG",
	"Teenage Engineering AB",
	"Tunstall Nordic AB",
	"Svep Design Center AB",
	"GreenPeak Technologies BV",
	"Sphinx Electronics GmbH & Co KG",
	"Atomation",
	"Nemik Consulting Inc",
	"RF INNOVATION",
	"Mini Solution Co., Ltd.",
	"Lumenetix, Inc",
	"2048450 Ontario Inc",
	"SPACEEK LTD",
	"Delta T Corporation",
	"Boston Scientific Corporation",
	"Nuviz, Inc.",
	"Real Time Automation, Inc.",
	"Kolibree",
	"vhf elektronik GmbH",
	"Bonsai Systems GmbH",
	"Fathom Systems Inc.",
	"Bellman & Symfon",
	"International Forte Group LLC",
	"CycleLabs Solutions inc.",
	"Codenex Oy",
	"Kynesim Ltd",
	"Palago AB",
	"INSIGMA INC.",
	"PMD Solutions",
	"Qingdao Realtime Technology Co., Ltd.",
	"BEGA Gantenbrink-Leuchten KG",
	"Pambor Ltd.",
	"Develco Products A/S",
	"iDesign s.r.l.",
	"TiVo Corp",
	"Control-J Pty Ltd",
	"Steelcase, Inc.",
	"iApartment co., ltd.",
	"Icom inc.",
	"Oxstren Wearable Technologies Private Limited",
	"Blue Spark Technologies",
	"FarSite Communications Limited",
	"mywerk system GmbH",
	"Sinosun Technology Co., Ltd.",
	"MIYOSHI ELECTRONICS CORPORATION",
	"POWERMAT LTD",
	"Occly LLC",
	"OurHub Dev IvS",
	"Pro-Mark, Inc.",
	"Dynometrics Inc.",
	"Quintrax Limited",
	"POS Tuning Udo Vosshenrich GmbH & Co. KG",
	"Multi Care Systems B.V.",
	"Revol Technologies Inc",
	"SKIDATA AG",
	"DEV TECNOLOGIA INDUSTRIA, COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME",
	"Centrica Connected Home",
	"Automotive Data Solutions Inc",
	"Igarashi Engineering",
	"Taelek Oy",
	"CP Electronics Limited",
	"Vectronix AG",
	"S-Labs Sp. z o.o.",
	"Companion Medical, Inc.",
	"BlueKitchen GmbH",
	"Matting AB",
	"SOREX - Wireless Solutions GmbH",
	"ADC Technology, Inc.",
	"Lynxemi Pte Ltd",
	"SENNHEISER electronic GmbH & Co. KG",
	"LMT Mercer Group, Inc",
	"Polymorphic Labs LLC",
	"Cochlear Limited",
	"METER Group, Inc. USA",
	"Ruuvi Innovations Ltd.",
	"Situne AS",
	"nVisti, LLC",
	"DyOcean",
	"Uhlmann & Zacher GmbH",
	"AND!XOR LLC",
	"tictote AB",
	"Vypin, LLC",
	"PNI Sensor Corporation",
	"ovrEngineered, LLC",
	"GT-tronics HK Ltd",
	"Herbert Waldmann GmbH & Co. KG",
	"Guangzhou FiiO Electronics Technology Co.,Ltd",
	"Vinetech Co., Ltd",
	"Dallas Logic Corporation",
	"BioTex, Inc.",
	"DISCOVERY SOUND TECHNOLOGY, LLC",
	"LINKIO SAS",
	"Harbortronics, Inc.",
	"Undagrid B.V.",
	"Shure Inc",
	"ERM Electronic Systems LTD",
	"BIOROWER Handelsagentur GmbH",
	"Weba Sport und Med. Artikel GmbH",
	"Kartographers Technologies Pvt. Ltd.",
	"The Shadow on the Moon",
	"mobike (Hong Kong) Limited",
	"Inuheat Group AB",
	"Swiftronix AB",
	"Diagnoptics Technologies",
	"Analog Devices, Inc.",
	"Soraa Inc.",
	"CSR Building Products Limited",
	"Crestron Electronics, Inc.",
	"Neatebox Ltd",
	"Draegerwerk AG & Co. KGaA",
	"AlbynMedical",
	"Averos FZCO",
	"VIT Initiative, LLC",
	"Statsports International",
	"Sospitas, s.r.o.",
	"Dmet Products Corp.",
	"Mantracourt Electronics Limited",
	"TeAM Hutchins AB",
	"Seibert Williams Glass, LLC",
	"Insta GmbH",
	"Svantek Sp. z o.o.",
	"Shanghai Flyco Electrical Appliance Co., Ltd.",
	"Thornwave Labs Inc",
	"Steiner-Optik GmbH",
	"Novo Nordisk A/S",
	"Enflux Inc.",
	"Safetech Products LLC",
	"GOOOLED S.R.L.",
	"DOM Sicherheitstechnik GmbH & Co. KG",
	"Olympus Corporation",
	"KTS GmbH",
	"Anloq Technologies Inc.",
	"Queercon, Inc",
	"5th Element Ltd",
	"Gooee Limited",
	"LUGLOC LLC",
	"Blincam, Inc.",
	"FUJIFILM Corporation",
	"RandMcNally",
	"Franceschi Marina snc",
	"Engineered Audio, LLC.",
	"IOTTIVE (OPC) PRIVATE LIMITED",
	"4MOD Technology",
	"Lutron Electronics Co., Inc.",
	"Emerson",
	"Guardtec, Inc.",
	"REACTEC LIMITED",
	"EllieGrid",
	"Under Armour",
	"Woodenshark",
	"Avack Oy",
	"Smart Solution Technology, Inc.",
	"REHABTRONICS INC.",
	"STABILO International",
	"Busch Jaeger Elektro GmbH",
	"Pacific Bioscience Laboratories, Inc",
	"Bird Home Automation GmbH",
	"Motorola Solutions",
	"R9 Technology, Inc.",
	"Auxivia",
	"DaisyWorks, Inc",
	"Kosi Limited",
	"Theben AG",
	"InDreamer Techsol Private Limited",
	"Cerevast Medical",
	"ZanCompute Inc.",
	"Pirelli Tyre S.P.A.",
	"McLear Limited",
	"Shenzhen Huiding Technology Co.,Ltd.",
	"Convergence Systems Limited",
	"Interactio",
	"Androtec GmbH",
	"Benchmark Drives GmbH & Co. KG",
	"SwingLync L. L. C.",
	"Tapkey GmbH",
	"Woosim Systems Inc.",
	"Microsemi Corporation",
	"Wiliot LTD.",
	"Polaris IND",
	"Specifi-Kali LLC",
	"Locoroll, Inc",
	"PHYPLUS Inc",
	"Inplay Technologies LLC",
	"Hager",
	"Yellowcog",
	"Axes System sp. z o. o.",
	"myLIFTER Inc.",
	"Shake-on B.V.",
	"Vibrissa Inc.",
	"OSRAM GmbH",
	"TRSystems GmbH",
	"Yichip Microelectronics (Hangzhou) Co.,Ltd.",
	"Foundation Engineering LLC",
	"UNI-ELECTRONICS, INC.",
	"Brookfield Equinox LLC",
	"Soprod SA",
	"9974091 Canada Inc.",
	"FIBRO GmbH",
	"RB Controls Co., Ltd.",
	"Footmarks",
	"Amtronic Sverige AB (formerly Amcore AB)",
	"MAMORIO.inc",
	"Tyto Life LLC",
	"Leica Camera AG",
	"Angee Technologies Ltd.",
	"EDPS",
	"OFF Line Co., Ltd.",
	"Detect Blue Limited",
	"Setec Pty Ltd",
	"Target Corporation",
	"IAI Corporation",
	"NS Tech, Inc.",
	"MTG Co., Ltd.",
	"Hangzhou iMagic Technology Co., Ltd",
	"HONGKONG NANO IC TECHNOLOGIES CO., LIMITED",
	"Honeywell International Inc.",
	"Albrecht JUNG",
	"Lunera Lighting Inc.",
	"Lumen UAB",
	"Keynes Controls Ltd",
	"Novartis AG",
	"Geosatis SA",
	"EXFO, Inc.",
	"LEDVANCE GmbH",
	"Center ID Corp.",
	"Adolene, Inc.",
	"D&M Holdings Inc.",
	"CRESCO Wireless, Inc.",
	"Nura Operations Pty Ltd",
	"Frontiergadget, Inc.",
	"Smart Component Technologies Limited",
	"ZTR Control Systems LLC",
	"MetaLogics Corporation",
	"Medela AG",
	"OPPLE Lighting Co., Ltd",
	"Savitech Corp.,",
	"prodigy",
	"Screenovate Technologies Ltd",
	"TESA SA",
	"CLIM8 LIMITED",
	"Silergy Corp",
	"SilverPlus, Inc",
	"Sharknet srl",
	"Mist Systems, Inc.",
	"MIWA LOCK CO.,Ltd",
	"OrthoSensor, Inc.",
	"Candy Hoover Group s.r.l",
	"Apexar Technologies S.A.",
	"LOGICDATA d.o.o.",
	"Knick Elektronische Messgeraete GmbH & Co. KG",
	"Smart Technologies and Investment Limited",
	"Linough Inc.",
	"Advanced Electronic Designs, Inc.",
	"Carefree Scott Fetzer Co Inc",
	"Sensome",
	"FORTRONIK storitve d.o.o.",
	"Sinnoz",
	"Versa Networks, Inc.",
	"Sylero",
	"Avempace SARL",
	"Nintendo Co., Ltd.",
	"National Instruments",
	"KROHNE Messtechnik GmbH",
	"Otodynamics Ltd",
	"Arwin Technology Limited",
	"benegear, inc.",
	"Newcon Optik",
	"CANDY HOUSE, Inc.",
	"FRANKLIN TECHNOLOGY INC",
	"Lely",
	"Valve Corporation",
	"Hekatron Vertriebs GmbH",
	"PROTECH S.A.S. DI GIRARDI ANDREA & C.",
	"Sarita CareTech APS (formerly Sarita CareTech IVS)",
	"Finder S.p.A.",
	"Thalmic Labs Inc.",
	"Steinel Vertrieb GmbH",
	"Beghelli Spa",
	"Beijing Smartspace Technologies Inc.",
	"CORE TRANSPORT TECHNOLOGIES NZ LIMITED",
	"Xiamen Everesports Goods Co., Ltd",
	"Bodyport Inc.",
	"Audionics System, INC.",
	"Flipnavi Co.,Ltd.",
	"Rion Co., Ltd.",
	"Long Range Systems, LLC",
	"Redmond Industrial Group LLC",
	"VIZPIN INC.",
	"BikeFinder AS",
	"Consumer Sleep Solutions LLC",
	"PSIKICK, INC.",
	"AntTail.com",
	"Lighting Science Group Corp.",
	"AFFORDABLE ELECTRONICS INC",
	"Integral Memroy Plc",
	"Globalstar, Inc.",
	"True Wearables, Inc.",
	"Wellington Drive Technologies Ltd",
	"Ensemble Tech Private Limited",
	"OMNI Remotes",
	"Duracell U.S. Operations Inc.",
	"Toor Technologies LLC",
	"Instinct Performance",
	"Beco, Inc",
	"Scuf Gaming International, LLC",
	"ARANZ Medical Limited",
	"LYS TECHNOLOGIES LTD",
	"Breakwall Analytics, LLC",
	"Code Blue Communications",
	"Gira Giersiepen GmbH & Co. KG",
	"Hearing Lab Technology",
	"LEGRAND",
	"Derichs GmbH",
	"ALT-TEKNIK LLC",
	"Star Technologies",
	"START TODAY CO.,LTD.",
	"Maxim Integrated Products",
	"MERCK Kommanditgesellschaft auf Aktien",
	"Jungheinrich Aktiengesellschaft",
	"Oculus VR, LLC",
	"HENDON SEMICONDUCTORS PTY LTD",
	"Pur3 Ltd",
	"Viasat Group S.p.A.",
	"IZITHERM",
	"Spaulding Clinical Research",
	"Kohler Company",
	"Inor Process AB",
	"My Smart Blinds",
	"RadioPulse Inc",
	"rapitag GmbH",
	"Lazlo326, LLC.",
	"Teledyne Lecroy, Inc.",
	"Dataflow Systems Limited",
	"Macrogiga Electronics",
	"Tandem Diabetes Care",
	"Polycom, Inc.",
	"Fisher & Paykel Healthcare",
	"RCP Software Oy",
	"Shanghai Xiaoyi Technology Co.,Ltd.",
	"ADHERIUM(NZ) LIMITED",
	"Axiomware Systems Incorporated",
	"O. E. M. Controls, Inc.",
	"Kiiroo BV",
	"Telecon Mobile Limited",
	"Sonos Inc",
	"Tom Allebrandi Consulting",
	"Monidor",
	"Tramex Limited",
	"Nofence AS",
	"GoerTek Dynaudio Co., Ltd.",
	"INIA",
	"CARMATE MFG.CO.,LTD",
	"ONvocal",
	"NewTec GmbH",
	"Medallion Instrumentation Systems",
	"CAREL INDUSTRIES S.P.A.",
	"Parabit Systems, Inc.",
	"White Horse Scientific ltd",
	"verisilicon",
	"Elecs Industry Co.,Ltd.",
	"Beijing Pinecone Electronics Co.,Ltd.",
	"Ambystoma Labs Inc.",
	"Suzhou Pairlink Network Technology",
	"igloohome",
	"Oxford Metrics plc",
	"Leviton Mfg. Co., Inc.",
	"ULC Robotics Inc.",
	"RFID Global by Softwork SrL",
	"Real-World-Systems Corporation",
	"Nalu Medical, Inc.",
	"P.I.Engineering",
	"Grote Industries",
	"Runtime, Inc.",
	"Codecoup sp. z o.o. sp. k.",
	"SELVE GmbH & Co. KG",
	"Smart Animal Training Systems, LLC",
	"Lippert Components, INC",
	"SOMFY SAS",
	"TBS Electronics B.V.",
	"MHL Custom Inc",
	"LucentWear LLC",
	"WATTS ELECTRONICS",
	"RJ Brands LLC",
	"V-ZUG Ltd",
	"Biowatch SA",
	"Anova Applied Electronics",
	"Lindab AB",
	"frogblue TECHNOLOGY GmbH",
	"Acurable Limited",
	"LAMPLIGHT Co., Ltd.",
	"TEGAM, Inc.",
	"Zhuhai Jieli technology Co.,Ltd",
	"modum.io AG",
	"Farm Jenny LLC",
	"Toyo Electronics Corporation",
	"Applied Neural Research Corp",
	"Avid Identification Systems, Inc.",
	"Petronics Inc.",
	"essentim GmbH",
	"QT Medical INC.",
	"VIRTUALCLINIC.DIRECT LIMITED",
	"Viper Design LLC",
	"Human, Incorporated",
	"stAPPtronics GmbH",
	"Elemental Machines, Inc.",
	"Taiyo Yuden Co., Ltd",
	"INEO ENERGY& SYSTEMS",
	"Motion Instruments Inc.",
	"PressurePro",
	"COWBOY",
	"iconmobile GmbH",
	"ACS-Control-System GmbH",
	"Bayerische Motoren Werke AG",
	"Gycom Svenska AB",
	"Fuji Xerox Co., Ltd",
	"Glide Inc.",
	"SIKOM AS",
	"beken",
	"The Linux Foundation",
	"Try and E CO.,LTD.",
	"SeeScan",
	"Clearity, LLC",
	"GS TAG",
	"DPTechnics",
	"TRACMO, INC.",
	"Anki Inc.",
	"Hagleitner Hygiene International GmbH",
	"Konami Sports Life Co., Ltd.",
	"Arblet Inc.",
	"Masbando GmbH",
	"Innoseis",
	"Niko nv",
	"Wellnomics Ltd",
	"iRobot Corporation",
	"Schrader Electronics",
	"Geberit International AG",
	"Fourth Evolution Inc",
	"Cell2Jack LLC",
	"FMW electronic Futterer u. Maier-Wolf OHG",
	"John Deere",
	"Rookery Technology Ltd",
	"KeySafe-Cloud",
	"BUCHI Labortechnik AG",
	"IQAir AG",
	"Triax Technologies Inc",
	"Vuzix Corporation",
	"TDK Corporation",
	"Blueair AB",
	"Signify Netherlands",
	"ADH GUARDIAN USA LLC",
	"Beurer GmbH",
	"Playfinity AS",
	"Hans Dinslage GmbH",
	"OnAsset Intelligence, Inc.",
	"INTER ACTION Corporation",
	"OS42 UG (haftungsbeschraenkt)",
	"WIZCONNECTED COMPANY LIMITED",
	"Audio-Technica Corporation",
	"Six Guys Labs, s.r.o.",
	"R.W. Beckett Corporation",
	"silex technology, inc.",
	"Univations Limited",
	"SENS Innovation ApS",
	"Diamond Kinetics, Inc.",
	"Phrame Inc.",
	"Forciot Oy",
	"Noordung d.o.o.",
	"Beam Labs, LLC",
	"Philadelphia Scientific (U.K.) Limited",
	"Biovotion AG",
	"Square Panda, Inc.",
	"Amplifico",
	"WEG S.A.",
	"Ensto Oy",
	"PHONEPE PVT LTD",
	"Lunatico Astronomia SL",
	"MinebeaMitsumi Inc.",
	"ASPion GmbH",
	"Vossloh-Schwabe Deutschland GmbH",
	"Procept",
	"ONKYO Corporation",
	"Asthrea D.O.O.",
	"Fortiori Design LLC",
	"Hugo Muller GmbH & Co KG",
	"Wangi Lai PLT",
	"Fanstel Corp",
	"Crookwood",
	"ELECTRONICA INTEGRAL DE SONIDO S.A.",
	"GiP Innovation Tools GmbH",
	"LX SOLUTIONS PTY LIMITED",
	"Shenzhen Minew Technologies Co., Ltd.",
	"Prolojik Limited",
	"Kromek Group Plc",
	"Contec Medical Systems Co., Ltd.",
	"Xradio Technology Co.,Ltd.",
	"The Indoor Lab, LLC",
	"LDL TECHNOLOGY",
	"Parkifi",
	"Revenue Collection Systems FRANCE SAS",
	"Bluetrum Technology Co.,Ltd",
	"makita corporation",
	"Apogee Instruments",
	"BM3",
	"SGV Group Holding GmbH & Co. KG",
	"MED-EL",
	"Ultune Technologies",
	"Ryeex Technology Co.,Ltd.",
	"Open Research Institute, Inc.",
	"Scale-Tec, Ltd",
	"Zumtobel Group AG",
	"iLOQ Oy",
	"KRUXWorks Technologies Private Limited",
	"Digital Matter Pty Ltd",
	"Coravin, Inc.",
	"Stasis Labs, Inc.",
	"ITZ Innovations- und Technologiezentrum GmbH",
	"Meggitt SA",
	"Ledlenser GmbH & Co. KG",
	"Renishaw PLC",
	"ZhuHai AdvanPro Technology Company Limited",
	"Meshtronix Limited",
	"Payex Norge AS",
	"UnSeen Technologies Oy",
	"Zound Industries International AB",
	"Sesam Solutions BV",
	"PixArt Imaging Inc.",
	"Panduit Corp.",
	"Alo AB",
	"Ricoh Company Ltd",
	"RTC Industries, Inc.",
	"Mode Lighting Limited",
	"Particle Industries, Inc.",
	"Advanced Telemetry Systems, Inc.",
	"RHA TECHNOLOGIES LTD",
	"Pure International Limited",
	"WTO Werkzeug-Einrichtungen GmbH",
	"Spark Technology Labs Inc.",
	"Bleb Technology srl",
	"Livanova USA, Inc.",
	"Brady Worldwide Inc.",
	"DewertOkin GmbH",
	"Ztove ApS",
	"Venso EcoSolutions AB",
	"Eurotronik Kranj d.o.o.",
	"Hug Technology Ltd",
	"Gema Switzerland GmbH",
	"Buzz Products Ltd.",
	"Kopi",
	"Innova Ideas Limited",
	"BeSpoon",
	"Deco Enterprises, Inc.",
	"Expai Solutions Private Limited",
	"Innovation First, Inc.",
	"SABIK Offshore GmbH",
	"4iiii Innovations Inc.",
	"The Energy Conservatory, Inc.",
	"I.FARM, INC.",
	"Tile, Inc.",
	"Form Athletica Inc.",
	"MbientLab Inc",
	"NETGRID S.N.C. DI BISSOLI MATTEO, CAMPOREALE SIMONE, TOGNETTI FEDERICO",
	"Mannkind Corporation",
	"Trade FIDES a.s.",
	"Photron Limited",
	"Eltako GmbH",
	"Dermalapps, LLC",
	"Greenwald Industries",
	"inQs Co., Ltd.",
	"Cherry GmbH",
	"Amsted Digital Solutions Inc.",
	"Tacx b.v.",
	"Raytac Corporation",
	"Jiangsu Teranovo Tech Co., Ltd.",
	"Changzhou Sound Dragon Electronics and Acoustics Co., Ltd",
	"JetBeep Inc.",
	"Razer Inc.",
	"JRM Group Limited",
	"Eccrine Systems, Inc.",
	"Curie Point AB",
	"Georg Fischer AG",
	"Hach - Danaher",
	"T&A Laboratories LLC",
	"Koki Holdings Co., Ltd.",
	"Gunakar Private Limited",
	"Stemco Products Inc",
	"Wood IT Security, LLC",
	"RandomLab SAS",
	"Adero, Inc. (formerly as TrackR, Inc.)",
	"Dragonchip Limited",
	"Noomi AB",
	"Vakaros LLC",
	"Delta Electronics, Inc.",
	"FlowMotion Technologies AS",
	"OBIQ Location Technology Inc.",
	"Cardo Systems, Ltd",
	"Globalworx GmbH",
	"Nymbus, LLC",
	"Sanyo Techno Solutions Tottori Co., Ltd.",
	"TEKZITEL PTY LTD",
	"Roambee Corporation",
	"Chipsea Technologies (ShenZhen) Corp.",
	"GD Midea Air-Conditioning Equipment Co., Ltd.",
	"Soundmax Electronics Limited",
	"Produal Oy",
	"HMS Industrial Networks AB",
	"Ingchips Technology Co., Ltd.",
	"InnovaSea Systems Inc.",
	"SenseQ Inc.",
	"Shoof Technologies",
	"BRK Brands, Inc.",
	"SimpliSafe, Inc.",
	"Tussock Innovation 2013 Limited",
	"The Hablab ApS",
	"Sencilion Oy",
	"Wabilogic Ltd.",
	"Sociometric Solutions, Inc.",
	"iCOGNIZE GmbH",
	"ShadeCraft, Inc",
	"Beflex Inc.",
	"Beaconzone Ltd",
	"Leaftronix Analogic Solutions Private Limited",
	"TWS Srl",
	"ABB Oy",
	"HitSeed Oy",
	"Delcom Products Inc.",
	"CAME S.p.A.",
	"Alarm.com Holdings, Inc",
	"Measurlogic Inc.",
	"King I Electronics.Co.,Ltd",
	"Dream Labs GmbH",
	"Urban Compass, Inc",
	"Simm Tronic Limited",
	"Somatix Inc",
	"Storz & Bickel GmbH & Co. KG",
	"MYLAPS B.V.",
	"Shenzhen Zhongguang Infotech Technology Development Co., Ltd",
	"Dyeware, LLC",
	"Dongguan SmartAction Technology Co.,Ltd.",
	"DIG Corporation",
	"FIOR & GENTZ",
	"Belparts N.V.",
	"Etekcity Corporation",
	"Meyer Sound Laboratories, Incorporated",
	"CeoTronics AG",
	"TriTeq Lock and Security, LLC",
	"DYNAKODE TECHNOLOGY PRIVATE LIMITED",
	"Sensirion AG",
	"JCT Healthcare Pty Ltd",
	"FUBA Automotive Electronics GmbH",
	"AW Company",
	"Shanghai Mountain View Silicon Co.,Ltd.",
	"Zliide Technologies ApS",
	"Automatic Labs, Inc.",
	"Industrial Network Controls, LLC",
	"Intellithings Ltd.",
	"Navcast, Inc.",
	"Hubbell Lighting, Inc.",
	"Avaya ",
	"Milestone AV Technologies LLC",
	"Alango Technologies Ltd",
	"Spinlock Ltd",
	"Aluna",
	"OPTEX CO.,LTD.",
	"NIHON DENGYO KOUSAKU",
	"VELUX A/S",
	"Almendo Technologies GmbH",
	"Zmartfun Electronics, Inc.",
	"SafeLine Sweden AB",
	"Houston Radar LLC",
	"Sigur",
	"J Neades Ltd",
	"Avantis Systems Limited",
	"ALCARE Co., Ltd.",
	"Chargy Technologies, SL",
	"Shibutani Co., Ltd.",
	"Trapper Data AB",
	"Alfred International Inc.",
	"Near Field Solutions Ltd",
	"Vigil Technologies Inc.",
	"Vitulo Plus BV",
	"WILKA Schliesstechnik GmbH",
	"BodyPlus Technology Co.,Ltd",
	"happybrush GmbH",
	"Enequi AB",
	"Sartorius AG",
	"Tom Communication Industrial Co.,Ltd.",
	"ESS Embedded System Solutions Inc.",
	"Mahr GmbH",
	"Redpine Signals Inc",
	"TraqFreq LLC",
	"PAFERS TECH",
	"Akciju sabiedriba \"SAF TEHNIKA\"",
	"Beijing Jingdong Century Trading Co., Ltd.",
	"JBX Designs Inc.",
	"AB Electrolux",
	"Wernher von Braun Center for ASdvanced Research",
	"Essity Hygiene and Health Aktiebolag",
	"Be Interactive Co., Ltd",
	"Carewear Corp.",
	"Huf Hülsbeck & Fürst GmbH & Co. KG",
	"Element Products, Inc.",
	"Beijing Winner Microelectronics Co.,Ltd",
	"SmartSnugg Pty Ltd",
	"FiveCo Sarl",
	"California Things Inc.",
	"Audiodo AB",
	"ABAX AS",
	"Bull Group Company Limited",
	"Respiri Limited",
	"MindPeace Safety LLC",
	"Vgyan Solutions",
	"Altonics",
	"iQsquare BV",
	"IDIBAIX enginneering",
	"ECSG",
	"REVSMART WEARABLE HK CO LTD",
	"Precor",
	"F5 Sports, Inc",
	"exoTIC Systems",
	"DONGGUAN HELE ELECTRONICS CO., LTD",
	"Dongguan Liesheng Electronic Co.Ltd",
	"Oculeve, Inc.",
	"Clover Network, Inc.",
	"Xiamen Eholder Electronics Co.Ltd",
	"Ford Motor Company",
	"Guangzhou SuperSound Information Technology Co.,Ltd",
	"Tedee Sp. z o.o.",
	"PHC Corporation",
	"STALKIT AS",
	"Eli Lilly and Company",
	"SwaraLink Technologies",
	"JMR embedded systems GmbH",
	"Bitkey Inc.",
	"GWA Hygiene GmbH",
	"Safera Oy",
	"Open Platform Systems LLC",
	"OnePlus Electronics (Shenzhen) Co., Ltd.",
	"Wildlife Acoustics, Inc.",
	"ABLIC Inc.",
	"Dairy Tech, Inc.",
	"Iguanavation, Inc.",
	"DiUS Computing Pty Ltd",
	"UpRight Technologies LTD",
	"FrancisFund, LLC",
	"LLC Navitek",
	"Glass Security Pte Ltd",
	"Jiangsu Qinheng Co., Ltd.",
	"Chandler Systems Inc.",
	"Fantini Cosmi s.p.a.",
	"Acubit ApS",
	"Beijing Hao Heng Tian Tech Co., Ltd.",
	"Bluepack S.R.L.",
	"Beijing Unisoc Technologies Co., Ltd.",
	"HITIQ LIMITED",
	"MAC SRL",
	"DML LLC",
	"Sanofi",
	"SOCOMEC",
	"WIZNOVA, Inc.",
	"Seitec Elektronik GmbH",
	"OR Technologies Pty Ltd",
	"GuangZhou KuGou Computer Technology Co.Ltd",
	"DIAODIAO (Beijing) Technology Co., Ltd.",
	"Illusory Studios LLC",
	"Sarvavid Software Solutions LLP",
	"iopool s.a.",
	"Amtech Systems, LLC",
	"EAGLE DETECTION SA",
	"MEDIATECH S.R.L.",
	"Hamilton Professional Services of Canada Incorporated",
	"Changsha JEMO IC Design Co.,Ltd",
	"Elatec GmbH",
	"JLG Industries, Inc.",
	"Michael Parkin",
	"Brother Industries, Ltd",
	"Lumens For Less, Inc",
	"ELA Innovation",
	"umanSense AB",
	"Shanghai InGeek Cyber Security Co., Ltd.",
	"HARMAN CO.,LTD.",
	"Smart Sensor Devices AB",
	"Antitronics Inc.",
	"RHOMBUS SYSTEMS, INC.",
	"Katerra Inc.",
	"Remote Solution Co., LTD.",
	"Vimar SpA",
	"Mantis Tech LLC",
	"TerOpta Ltd",
	"PIKOLIN S.L.",
	"WWZN Information Technology Company Limited",
	"Voxx International",
	"ART AND PROGRAM, INC.",
	"NITTO DENKO ASIA TECHNICAL CENTRE PTE. LTD.",
	"Peloton Interactive Inc.",
	"Force Impact Technologies",
	"Dmac Mobile Developments, LLC",
	"Engineered Medical Technologies",
	"Noodle Technology inc",
	"Graesslin GmbH",
	"WuQi technologies, Inc.",
	"Successful Endeavours Pty Ltd",
	"InnoCon Medical ApS",
	"Corvex Connected Safety",
	"Thirdwayv Inc.",
	"Echoflex Solutions Inc.",
	"C-MAX Asia Limited",
	"4eBusiness GmbH",
	"Cyber Transport Control GmbH",
	"Cue",
	"KOAMTAC INC.",
	"Loopshore Oy",
	"Niruha Systems Private Limited",
	"AmaterZ, Inc.",
	"radius co., ltd.",
	"Sensority, s.r.o.",
	"Sparkage Inc.",
	"Glenview Software Corporation",
	"Finch Technologies Ltd.",
	"Qingping Technology (Beijing) Co., Ltd.",
	"DeviceDrive AS",
	"ESEMBER LIMITED LIABILITY COMPANY",
	"audifon GmbH & Co. KG",
	"O2 Micro, Inc.",
	"HLP Controls Pty Limited",
	"Pangaea Solution",
	"BubblyNet, LLC",
	"Reserved for future use (?)",
	"The Wildflower Foundation",
	"Optikam Tech Inc.",
	"MINIBREW HOLDING B.V",
	"Cybex GmbH",
	"FUJIMIC NIIGATA, INC.",
	"Hanna Instruments, Inc.",
	"KOMPAN A/S",
	"Scosche Industries, Inc.",
	"Provo Craft",
	"AEV spol. s r.o.",
	"The Coca-Cola Company",
	"GASTEC CORPORATION",
	"StarLeaf Ltd",
	"Water-i.d. GmbH",
	"HoloKit, Inc.",
	"PlantChoir Inc.",
	"GuangDong Oppo Mobile Telecommunications Corp., Ltd.",
	"CST ELECTRONICS (PROPRIETARY) LIMITED",
	"Sky UK Limited",
	"Digibale Pty Ltd",
	"Smartloxx GmbH",
	"Pune Scientific LLP",
	"Regent Beleuchtungskorper AG",
	"Apollo Neuroscience, Inc.",
	"Roku, Inc.",
	"Comcast Cable",
	"Xiamen Mage Information Technology Co., Ltd.",
	"RAB Lighting, Inc.",
	"Musen Connect, Inc.",
	"Zume, Inc.",
	"conbee GmbH",
	"Bruel & Kjaer Sound & Vibration",
	"The Kroger Co.",
	"Granite River Solutions, Inc.",
	"LoupeDeck Oy",
	"New H3C Technologies Co.,Ltd",
	"Aurea Solucoes Tecnologicas Ltda.",
	"Hong Kong Bouffalo Lab Limited",
	"GV Concepts Inc.",
	"Thomas Dynamics, LLC",
	"Moeco IOT Inc.",
	"2N TELEKOMUNIKACE a.s.",
	"Hormann KG Antriebstechnik",
	"CRONO CHIP, S.L.",
	"Soundbrenner Limited",
	"ETABLISSEMENTS GEORGES RENAULT",
	"iSwip",
	"Epona Biotec Limited",
	"Battery-Biz Inc.",
	"EPIC S.R.L.",
	"KD CIRCUITS LLC",
	"Genedrive Diagnostics Ltd",
	"Axentia Technologies AB",
	"REGULA Ltd.",
	"Biral AG",
	"A.W. Chesterton Company",
	"Radinn AB",
	"CIMTechniques, Inc.",
	"Johnson Health Tech NA",
	"June Life, Inc.",
	"Bluenetics GmbH",
	"iaconicDesign Inc.",
	"WRLDS Creations AB",
	"Skullcandy, Inc.",
	"Modul-System HH AB",
	"West Pharmaceutical Services, Inc.",
	"Barnacle Systems Inc.",
	"Smart Wave Technologies Canada Inc",
	"Shanghai Top-Chip Microelectronics Tech. Co., LTD",
	"NeoSensory, Inc.",
	"Hangzhou Tuya Information Technology Co., Ltd",
	"Shanghai Panchip Microelectronics Co., Ltd",
	"React Accessibility Limited",
	"LIVNEX Co.,Ltd.",
	"Kano Computing Limited",
	"hoots classic GmbH",
	"ecobee Inc.",
	"Nanjing Qinheng Microelectronics Co., Ltd",
	"SOLUTIONS AMBRA INC.",
	"Micro-Design, Inc.",
	"STARLITE Co., Ltd.",
	"Remedee Labs",
	"ThingOS GmbH",
	"Linear Circuits",
	"Unlimited Engineering SL",
	"Snap-on Incorporated",
	"Edifier International Limited",
	"Lucie Labs",
	"Alfred Kaercher SE & Co. KG",
	"Audiowise Technology Inc.",
	"Geeksme S.L.",
	"Minut, Inc.",
	"Autogrow Systems Limited",
	"Komfort IQ, Inc.",
	"Packetcraft, Inc.",
	"Häfele GmbH & Co KG",
	"ShapeLog, Inc.",
	"NOVABASE S.R.L.",
	"Frecce LLC",
	"Joule IQ, INC.",
	"KidzTek LLC",
	"Aktiebolaget Sandvik Coromant",
	"e-moola.com Pty Ltd",
	"GSM Innovations Pty Ltd",
	"SERENE GROUP, INC",
	"DIGISINE ENERGYTECH CO. LTD.",
	"MEDIRLAB Orvosbiologiai Fejleszto Korlatolt Felelossegu Tarsasag",
	"Byton North America Corporation",
	"Shenzhen TonliScience and Technology Development Co.,Ltd",
	"Cesar Systems Ltd.",
	"quip NYC Inc.",
	"Direct Communication Solutions, Inc.",
	"Klipsch Group, Inc.",
	"Access Co., Ltd",
	"Renault SA",
	"JSK CO., LTD.",
	"BIROTA",
	"maxon motor ltd.",
	"Optek",
	"CRONUS ELECTRONICS LTD",
	"NantSound, Inc.",
	"Domintell s.a.",
	"Andon Health Co.,Ltd",
	"Urbanminded Ltd",
	"TYRI Sweden AB",
	"ECD Electronic Components GmbH Dresden",
	"SISTEMAS KERN, SOCIEDAD ANÓMINA",
	"Trulli Audio",
	"Altaneos",
	"Nanoleaf Canada Limited",
	"Ingy B.V.",
	"Azbil Co.",
	"TATTCOM LLC",
	"Paradox Engineering SA",
	"LECO Corporation",
	"Becker Antriebe GmbH",
	"Mstream Technologies., Inc.",
	"Flextronics International USA Inc.",
	"Ossur hf.",
	"SKC Inc",
	"SPICA SYSTEMS LLC",
	"Wangs Alliance Corporation",
	"tatwah SA",
	"Hunter Douglas Inc",
	"Shenzhen Conex",
	"DIM3",
	"Bobrick Washroom Equipment, Inc.",
	"Potrykus Holdings and Development LLC",
	"iNFORM Technology GmbH",
	"eSenseLab LTD",
	"Brilliant Home Technology, Inc.",
	"INOVA Geophysical, Inc.",
	"adafruit industries",
	"Nexite Ltd",
	"8Power Limited",
	"CME PTE. LTD.",
	"Hyundai Motor Company",
	"Kickmaker",
	"Shanghai Suisheng Information Technology Co., Ltd.",
	"HEXAGON",
	"Mitutoyo Corporation",
	"shenzhen fitcare electronics Co.,Ltd",
	"INGICS TECHNOLOGY CO., LTD.",
	"INCUS PERFORMANCE LTD.",
	"ABB S.p.A.",
	"Blippit AB",
	"Core Health and Fitness LLC",
	"Foxble, LLC",
	"Intermotive,Inc.",
	"Conneqtech B.V.",
	"RIKEN KEIKI CO., LTD.,",
	"Canopy Growth Corporation",
	"Bitwards Oy",
	"vivo Mobile Communication Co., Ltd.",
	"Etymotic Research, Inc.",
	"A puissance 3",
	"BPW Bergische Achsen Kommanditgesellschaft",
	"Piaggio Fast Forward",
	"BeerTech LTD",
	"Tokenize, Inc.",
	"Zorachka LTD",
	"D-Link Corp.",
	"Down Range Systems LLC",
	"General Luminaire (Shanghai) Co., Ltd.",
	"Tangshan HongJia electronic technology co., LTD.",
	"FRAGRANCE DELIVERY TECHNOLOGIES LTD",
	"Pepperl + Fuchs GmbH",
	"Dometic Corporation",
	"USound GmbH",
	"DNANUDGE LIMITED",
	"JUJU JOINTS CANADA CORP.",
	"Dopple Technologies B.V.",
	"ARCOM",
	"Biotechware SRL",
	"ORSO Inc.",
	"SafePort",
	"Carol Cole Company",
	"Embedded Fitness B.V.",
	"Yealink (Xiamen) Network Technology Co.,LTD",
	"Subeca, Inc.",
	"Cognosos, Inc.",
	"Pektron Group Limited",
	"Tap Sound System",
	"Helios Hockey, Inc.",
	"Canopy Growth Corporation",
	"Parsyl Inc",
};
const char *
btmanufacturer(int manufacturer)
{
	if (manufacturer >= nitems(bt_hcimanufacturer_strs))
		return ("invalid hci version");
	return (bt_hcimanufacturer_strs[manufacturer]);
}

const char * const bt_hciversion_strs[] = {
	"Bluetooth Core Specification 1.0b (Withdrawn)",
	"Bluetooth Core Specification 1.1 (Withdrawn)",
	"Bluetooth Core Specification 1.2 (Withdrawn)",
	"Bluetooth Core Specification 2.0 + EDR (Withdrawn)",
	"Bluetooth Core Specification 2.1 + EDR (Deprecated, to be withdrawn)",
	"Bluetooth Core Specification 3.0 + HS (Deprecated, to be withdrawn)",
	"Bluetooth Core Specification 4.0",
	"​Bluetooth Core Specification 4.1",
	"​​Bluetooth Core Specification 4.2",
	"Bluetooth Core Specification 5.0",
	"Bluetooth Core Specification 5.1",
	"Bluetooth Core Specification 5.2",
};
const char *
bthciversion(int hci_version)
{
	if (hci_version >= nitems(bt_hciversion_strs))
		return ("invalid hci version");
	return (bt_hciversion_strs[hci_version]);
}

const char * const bt_lmpversion_strs[] = {
	"Bluetooth Core Specification 1.0b (Withdrawn)",
	"Bluetooth Core Specification 1.1 (Withdrawn)",
	"Bluetooth Core Specification 1.2 (Withdrawn)",
	"Bluetooth Core Specification 2.0 + EDR (Withdrawn)",
	"Bluetooth Core Specification 2.1 + EDR (Deprecated, to be withdrawn)",
	"Bluetooth Core Specification 3.0 + HS (Deprecated, to be withdrawn)",
	"Bluetooth Core Specification 4.0",
	"​Bluetooth Core Specification 4.1",
	"​​Bluetooth Core Specification 4.2",
	"Bluetooth Core Specification 5.0",
	"Bluetooth Core Specification 5.1",
	"Bluetooth Core Specification 5.2",
};
const char *
btlmpversion(int lmp_vesion)
{
	if (lmp_vesion >= nitems(bt_lmpversion_strs))
		return ("invalid lmp version");
	return (bt_lmpversion_strs[lmp_vesion]);
}

/* bt_commandbitmask_strs nitems shall be multiple of 8 */
struct bt_commandbitmask_str {
	uint8_t		 byte;
	uint8_t		 bit;
	char		*desc;
} bt_commandbitmask_strs[] = {
	{ 0, 0, "HCI_Inquiry"},
	{ 0, 1, "HCI_Inquiry_Cancel"},
	{ 0, 2, "HCI_Periodic_Inquiry_Mode"},
	{ 0, 3, "HCI_Exit_Periodic_Inquiry_Mode"},
	{ 0, 4, "HCI_Create_Connection"},
	{ 0, 5, "HCI_Disconnect"},
	{ 0, 6, "HCI_Add_SCO_Connection (deprecated)"},
	{ 0, 7, "HCI_Create_Connection_Cancel"},
	{ 1, 0, "HCI_Accept_Connection_Request"},
	{ 1, 1, "HCI_Reject_Connection_Request"},
	{ 1, 2, "HCI_Link_Key_Request_Reply"},
	{ 1, 3, "HCI_Link_Key_Request_Negative_Reply"},
	{ 1, 4, "HCI_PIN_Code_Request_Reply"},
	{ 1, 5, "HCI_PIN_Code_Request_Negative_Reply"},
	{ 1, 6, "HCI_Change_Connection_Packet_Type"},
	{ 1, 7, "HCI_Authentication_Requested"},
	{ 2, 0, "HCI_Set_Connection_Encryption"},
	{ 2, 1, "HCI_Change_Connection_Link_Key"},
	{ 2, 2, "HCI_Master_Link_Key"},
	{ 2, 3, "HCI_Remote_Name_Request"},
	{ 2, 4, "HCI_Remote_Name_Request_Cancel"},
	{ 2, 5, "HCI_Read_Remote_Supported_Features"},
	{ 2, 6, "HCI_Read_Remote_Extended_Features"},
	{ 2, 7, "HCI_Read_Remote_Version_Information"},
	{ 3, 0, "HCI_Read_Clock_Offset"},
	{ 3, 1, "HCI_Read_LMP_Handle"},
	{ 3, 2, "Reserved for future use"},
	{ 3, 3, "Reserved for future use"},
	{ 3, 4, "Reserved for future use"},
	{ 3, 5, "Reserved for future use"},
	{ 3, 6, "Reserved for future use"},
	{ 3, 7, "Reserved for future use"},
	{ 4, 0, "Reserved for future use"},
	{ 4, 1, "HCI_Hold_Mode"},
	{ 4, 2, "HCI_Sniff_Mode"},
	{ 4, 3, "HCI_Exit_Sniff_Mode"},
	{ 4, 4, "Reserved for future use"},
	{ 4, 5, "Reserved for future use"},
	{ 4, 6, "HCI_QoS_Setup"},
	{ 4, 7, "HCI_Role_Discovery"},
	{ 5, 0, "HCI_Switch_Role"},
	{ 5, 1, "HCI_Read_Link_Policy_Settings"},
	{ 5, 2, "HCI_Write_Link_Policy_Settings"},
	{ 5, 3, "HCI_Read_Default_Link_Policy_Settings"},
	{ 5, 4, "HCI_Write_Default_Link_Policy_Settings"},
	{ 5, 5, "HCI_Flow_Specification"},
	{ 5, 6, "HCI_Set_Event_Mask"},
	{ 5, 7, "HCI_Reset"},
	{ 6, 0, "HCI_Set_Event_Filter"},
	{ 6, 1, "HCI_Flush"},
	{ 6, 2, "HCI_Read_PIN_Type"},
	{ 6, 3, "HCI_Write_PIN_Type"},
	{ 6, 4, "Reserved for future use"},
	{ 6, 5, "HCI_Read_Stored_Link_Key"},
	{ 6, 6, "HCI_Write_Stored_Link_Key"},
	{ 6, 7, "HCI_Delete_Stored_Link_Key"},
	{ 7, 0, "HCI_Write_Local_Name"},
	{ 7, 1, "HCI_Read_Local_Name"},
	{ 7, 2, "HCI_Read_Connection_Accept_Timeout"},
	{ 7, 3, "HCI_Write_Connection_Accept_Timeout"},
	{ 7, 4, "HCI_Read_Page_Timeout"},
	{ 7, 5, "HCI_Write_Page_Timeout"},
	{ 7, 6, "HCI_Read_Scan_Enable"},
	{ 7, 7, "HCI_Write_Scan_Enable"},
	{ 8, 0, "HCI_Read_Page_Scan_Activity"},
	{ 8, 1, "HCI_Write_Page_Scan_Activity"},
	{ 8, 2, "HCI_Read_Inquiry_Scan_Activity"},
	{ 8, 3, "HCI_Write_Inquiry_Scan_Activity"},
	{ 8, 4, "HCI_Read_Authentication_Enable"},
	{ 8, 5, "HCI_Write_Authentication_Enable"},
	{ 8, 6, "HCI_Read_Encryption_Mode (deprecated)"},
	{ 8, 7, "HCI_Write_Encryption_Mode (deprecated)"},
	{ 9, 0, "HCI_Read_Class_Of_Device"},
	{ 9, 1, "HCI_Write_Class_Of_Device"},
	{ 9, 2, "HCI_Read_Voice_Setting"},
	{ 9, 3, "HCI_Write_Voice_Setting"},
	{ 9, 4, "HCI_Read_Automatic_Flush_Timeout"},
	{ 9, 5, "HCI_Write_Automatic_Flush_Timeout"},
	{ 9, 6, "HCI_Read_Num_Broadcast_Retransmissions"},
	{ 9, 7, "HCI_Write_Num_Broadcast_Retransmissions"},
	{ 10, 0, "HCI_Read_Hold_Mode_Activity"},
	{ 10, 1, "HCI_Write_Hold_Mode_Activity"},
	{ 10, 2, "HCI_Read_Transmit_Power_Level"},
	{ 10, 3, "HCI_Read_Synchronous_Flow_Control_Enable"},
	{ 10, 4, "HCI_Write_Synchronous_Flow_Control_Enable"},
	{ 10, 5, "HCI_Set_Controller_To_Host_Flow_Control"},
	{ 10, 6, "HCI_Host_Buffer_Size"},
	{ 10, 7, "HCI_Host_Number_Of_Completed_Packets"},
	{ 11, 0, "HCI_Read_Link_Supervision_Timeout"},
	{ 11, 1, "HCI_Write_Link_Supervision_Timeout"},
	{ 11, 2, "HCI_Read_Number_Of_Supported_IAC"},
	{ 11, 3, "HCI_Read_Current_IAC_LAP"},
	{ 11, 4, "HCI_Write_Current_IAC_LAP"},
	{ 11, 5, "HCI_Read_Page_Scan_Mode_Period (deprecated)"},
	{ 11, 6, "HCI_Write_Page_Scan_Mode_Period (deprecated)"},
	{ 11, 7, "HCI_Read_Page_Scan_Mode (deprecated)"},
	{ 12, 0, "HCI_Write_Page_Scan_Mode (deprecated)"},
	{ 12, 1, "HCI_Set_AFH_Host_Channel_Classification"},
	{ 12, 2, "Reserved for future use"},
	{ 12, 3, "Reserved for future use"},
	{ 12, 4, "HCI_Read_Inquiry_Scan_Type"},
	{ 12, 5, "HCI_Write_Inquiry_Scan_Type"},
	{ 12, 6, "HCI_Read_Inquiry_Mode"},
	{ 12, 7, "HCI_Write_Inquiry_Mode"},
	{ 13, 0, "HCI_Read_Page_Scan_Type"},
	{ 13, 1, "HCI_Write_Page_Scan_Type"},
	{ 13, 2, "HCI_Read_AFH_Channel_Assessment_Mode"},
	{ 13, 3, "HCI_Write_AFH_Channel_Assessment_Mode"},
	{ 13, 4, "Reserved for future use"},
	{ 13, 5, "Reserved for future use"},
	{ 13, 6, "Reserved for future use"},
	{ 13, 7, "Reserved for future use"},
	{ 14, 0, "Reserved for future use"},
	{ 14, 1, "Reserved for future use"},
	{ 14, 2, "Reserved for future use"},
	{ 14, 3, "HCI_Read_Local_Version_Information"},
	{ 14, 4, "Reserved for future use"},
	{ 14, 5, "HCI_Read_Local_Supported_Features"},
	{ 14, 6, "HCI_Read_Local_Extended_Features"},
	{ 14, 7, "HCI_Read_Buffer_Size"},
	{ 15, 0, "HCI_Read_Country_Code (deprecated)"},
	{ 15, 1, "HCI_Read_BD_ADDR"},
	{ 15, 2, "HCI_Read_Failed_Contact_Counter"},
	{ 15, 3, "HCI_Reset_Failed_Contact_Counter"},
	{ 15, 4, "HCI_Read_Link_Quality"},
	{ 15, 5, "HCI_Read_RSSI"},
	{ 15, 6, "HCI_Read_AFH_Channel_Map"},
	{ 15, 7, "HCI_Read_Clock"},
	{ 16, 0, "HCI_Read_Loopback_Mode"},
	{ 16, 1, "HCI_Write_Loopback_Mode"},
	{ 16, 2, "HCI_Enable_Device_Under_Test_Mode"},
	{ 16, 3, "HCI_Setup_Synchronous_Connection_Request"},
	{ 16, 4, "HCI_Accept_Synchronous_Connection_Request"},
	{ 16, 5, "HCI_Reject_Synchronous_Connection_Request"},
	{ 16, 6, "Reserved for future use"},
	{ 16, 7, "Reserved for future use"},
	{ 17, 0, "HCI_Read_Extended_Inquiry_Response"},
	{ 17, 1, "HCI_Write_Extended_Inquiry_Response"},
	{ 17, 2, "HCI_Refresh_Encryption_Key"},
	{ 17, 3, "Reserved for future use"},
	{ 17, 4, "HCI_Sniff_Subrating"},
	{ 17, 5, "HCI_Read_Simple_Pairing_Mode"},
	{ 17, 6, "HCI_Write_Simple_Pairing_Mode"},
	{ 17, 7, "HCI_Read_Local_OOB_Data"},
	{ 18, 0, "HCI_Read_Inquiry_Response_Transmit_Power_Level"},
	{ 18, 1, "HCI_Write_Inquiry_Transmit_Power_Level"},
	{ 18, 2, "HCI_Read_Default_Erroneous_Data_Reporting"},
	{ 18, 3, "HCI_Write_Default_Erroneous_Data_Reporting"},
	{ 18, 4, "Reserved for future use"},
	{ 18, 5, "Reserved for future use"},
	{ 18, 6, "Reserved for future use"},
	{ 18, 7, "HCI_IO_Capability_Request_Reply"},
	{ 19, 0, "HCI_User_Confirmation_Request_Reply"},
	{ 19, 1, "HCI_User_Confirmation_Request_Negative_Reply"},
	{ 19, 2, "HCI_User_Passkey_Request_Reply"},
	{ 19, 3, "HCI_User_Passkey_Request_Negative_Reply"},
	{ 19, 4, "HCI_Remote_OOB_Data_Request_Reply"},
	{ 19, 5, "HCI_Write_Simple_Pairing_Debug_Mode"},
	{ 19, 6, "HCI_Enhanced_Flush"},
	{ 19, 7, "HCI_Remote_OOB_Data_Request_Negative_Reply"},
	{ 20, 0, "Reserved for future use"},
	{ 20, 1, "Reserved for future use"},
	{ 20, 2, "HCI_Send_Keypress_Notification"},
	{ 20, 3, "HCI_IO_Capability_Request_Negative_Reply"},
	{ 20, 4, "HCI_Read_Encryption_Key_Size"},
	{ 20, 5, "Reserved for future use"},
	{ 20, 6, "Reserved for future use"},
	{ 20, 7, "Reserved for future use"},
	{ 21, 0, "HCI_Create_Physical_Link"},
	{ 21, 1, "HCI_Accept_Physical_Link"},
	{ 21, 2, "HCI_Disconnect_Physical_Link"},
	{ 21, 3, "HCI_Create_Logical_Link"},
	{ 21, 4, "HCI_Accept_Logical_Link"},
	{ 21, 5, "HCI_Disconnect_Logical_Link"},
	{ 21, 6, "HCI_Logical_Link_Cancel"},
	{ 21, 7, "HCI_Flow_Spec_Modify"},
	{ 22, 0, "HCI_Read_Logical_Link_Accept_Timeout"},
	{ 22, 1, "HCI_Write_Logical_Link_Accept_Timeout"},
	{ 22, 2, "HCI_Set_Event_Mask_Page_2"},
	{ 22, 3, "HCI_Read_Location_Data"},
	{ 22, 4, "HCI_Write_Location_Data"},
	{ 22, 5, "HCI_Read_Local_AMP_Info"},
	{ 22, 6, "HCI_Read_Local_AMP_ASSOC"},
	{ 22, 7, "HCI_Write_Remote_AMP_ASSOC"},
	{ 23, 0, "HCI_Read_Flow_Control_Mode"},
	{ 23, 1, "HCI_Write_Flow_Control_Mode"},
	{ 23, 2, "HCI_Read_Data_Block_Size"},
	{ 23, 3, "Reserved for future use"},
	{ 23, 4, "Reserved for future use"},
	{ 23, 5, "HCI_Enable_AMP_Receiver_Reports"},
	{ 23, 6, "HCI_AMP_Test_End"},
	{ 23, 7, "HCI_AMP_Test"},
	{ 24, 0, "HCI_Read_Enhanced_Transmit_Power_Level"},
	{ 24, 1, "Reserved for future use"},
	{ 24, 2, "HCI_Read_Best_Effort_Flush_Timeout"},
	{ 24, 3, "HCI_Write_Best_Effort_Flush_Timeout"},
	{ 24, 4, "HCI_Short_Range_Mode"},
	{ 24, 5, "HCI_Read_LE_Host_Support"},
	{ 24, 6, "HCI_Write_LE_Host_Support"},
	{ 24, 7, "Reserved for future use"},
	{ 25, 0, "HCI_LE_Set_Event_Mask"},
	{ 25, 1, "HCI_LE_Read_Buffer_Size"},
	{ 25, 2, "HCI_LE_Read_Local_Supported_Features"},
	{ 25, 3, "Reserved for future use"},
	{ 25, 4, "HCI_LE_Set_Random_Address"},
	{ 25, 5, "HCI_LE_Set_Advertising_Parameters"},
	{ 25, 6, "HCI_LE_Read_Advertising_Physical_Channel_Tx_Power"},
	{ 25, 7, "HCI_LE_Set_Advertising_Data"},
	{ 26, 0, "HCI_LE_Set_Scan_Response_Data"},
	{ 26, 1, "HCI_LE_Set_Advertising_Enable"},
	{ 26, 2, "HCI_LE_Set_Scan_Parameters"},
	{ 26, 3, "HCI_LE_Set_Scan_Enable"},
	{ 26, 4, "HCI_LE_Create_Connection"},
	{ 26, 5, "HCI_LE_Create_Connection_Cancel"},
	{ 26, 6, "HCI_LE_Read_White_List_Size"},
	{ 26, 7, "HCI_LE_Clear_White_List"},
	{ 27, 0, "HCI_LE_Add_Device_To_White_List"},
	{ 27, 1, "HCI_LE_Remove_Device_From_White_List"},
	{ 27, 2, "HCI_LE_Connection_Update"},
	{ 27, 3, "HCI_LE_Set_Host_Channel_Classification"},
	{ 27, 4, "HCI_LE_Read_Channel_Map"},
	{ 27, 5, "HCI_LE_Read_Remote_Features"},
	{ 27, 6, "HCI_LE_Encrypt"},
	{ 27, 7, "HCI_LE_Rand"},
	{ 28, 0, "HCI_LE_Start_Encryption"},
	{ 28, 1, "HCI_LE_Long_Term_Key_Request_Reply"},
	{ 28, 2, "HCI_LE_Long_Term_Key_Request_Negative_Reply"},
	{ 28, 3, "HCI_LE_Read_Supported_States"},
	{ 28, 4, "HCI_LE_Receiver_Test [v1]"},
	{ 28, 5, "HCI_LE_Transmitter_Test [v1]"},
	{ 28, 6, "HCI_LE_Test_End"},
	{ 28, 7, "Reserved for future use"},
	{ 29, 0, "Reserved for future use"},
	{ 29, 1, "Reserved for future use"},
	{ 29, 2, "Reserved for future use"},
	{ 29, 3, "HCI_Enhanced_Setup_Synchronous_Connection"},
	{ 29, 4, "HCI_Enhanced_Accept_Synchronous_Connection"},
	{ 29, 5, "HCI_Read_Local_Supported_Codecs"},
	{ 29, 6, "HCI_Set_MWS_Channel_Parameters"},
	{ 29, 7, "HCI_Set_External_Frame_Configuration"},
	{ 30, 0, "HCI_Set_MWS_Signaling"},
	{ 30, 1, "HCI_Set_MWS_Transport_Layer"},
	{ 30, 2, "HCI_Set_MWS_Scan_Frequency_Table"},
	{ 30, 3, "HCI_Get_MWS_Transport_Layer_Configuration"},
	{ 30, 4, "HCI_Set_MWS_PATTERN_Configuration"},
	{ 30, 5, "HCI_Set_Triggered_Clock_Capture"},
	{ 30, 6, "HCI_Truncated_Page"},
	{ 30, 7, "HCI_Truncated_Page_Cancel"},
	{ 31, 0, "HCI_Set_Connectionless_Slave_Broadcast"},
	{ 31, 1, "HCI_Set_Connectionless_Slave_Broadcast_Receive"},
	{ 31, 2, "HCI_Start_Synchronization_Train"},
	{ 31, 3, "HCI_Receive_Synchronization_Train"},
	{ 31, 4, "HCI_Set_Reserved_LT_ADDR"},
	{ 31, 5, "HCI_Delete_Reserved_LT_ADDR"},
	{ 31, 6, "HCI_Set_Connectionless_Slave_Broadcast_Data"},
	{ 31, 7, "HCI_Read_Synchronization_Train_Parameters"},
	{ 32, 0, "HCI_Write_Synchronization_Train_Parameters"},
	{ 32, 1, "HCI_Remote_OOB_Extended_Data_Request_Reply"},
	{ 32, 2, "HCI_Read_Secure_Connections_Host_Support"},
	{ 32, 3, "HCI_Write_Secure_Connections_Host_Support"},
	{ 32, 4, "HCI_Read_Authenticated_Payload_Timeout"},
	{ 32, 5, "HCI_Write_Authenticated_Payload_Timeout"},
	{ 32, 6, "HCI_Read_Local_OOB_Extended_Data"},
	{ 32, 7, "HCI_Write_Secure_Connections_Test_Mode"},
	{ 33, 0, "HCI_Read_Extended_Page_Timeout"},
	{ 33, 1, "HCI_Write_Extended_Page_Timeout"},
	{ 33, 2, "HCI_Read_Extended_Inquiry_Length"},
	{ 33, 3, "HCI_Write_Extended_Inquiry_Length"},
	{ 33, 4, "HCI_LE_Remote_Connection_Parameter_Request_Reply"},
	{ 33, 5, "HCI_LE_Remote_Connection_Parameter_Request_Negative_Reply"},
	{ 33, 6, "HCI_LE_Set_Data_Length"},
	{ 33, 7, "HCI_LE_Read_Suggested_Default_Data_Length"},
	{ 34, 0, "HCI_LE_Write_Suggested_Default_Data_Length"},
	{ 34, 1, "HCI_LE_Read_Local_P-256_Public_Key"},
	{ 34, 2, "HCI_LE_Generate_DHKey [v1]"},
	{ 34, 3, "HCI_LE_Add_Device_To_Resolving_List"},
	{ 34, 4, "HCI_LE_Remove_Device_From_Resolving_List"},
	{ 34, 5, "HCI_LE_Clear_Resolving_List"},
	{ 34, 6, "HCI_LE_Read_Resolving_List_Size"},
	{ 34, 7, "HCI_LE_Read_Peer_Resolvable_Address"},
	{ 35, 0, "HCI_LE_Read_Local_Resolvable_Address"},
	{ 35, 1, "HCI_LE_Set_Address_Resolution_Enable"},
	{ 35, 2, "HCI_LE_Set_Resolvable_Private_Address_Timeout"},
	{ 35, 3, "HCI_LE_Read_Maximum_Data_Length"},
	{ 35, 4, "HCI_LE_Read_PHY"},
	{ 35, 5, "HCI_LE_Set_Default_PHY"},
	{ 35, 6, "HCI_LE_Set_PHY"},
	{ 35, 7, "HCI_LE_Receiver_Test [v2]"},
	{ 36, 0, "HCI_LE_Transmitter_Test [v2]"},
	{ 36, 1, "HCI_LE_Set_Advertising_Set_Random_Address"},
	{ 36, 2, "HCI_LE_Set_Extended_Advertising_Parameters"},
	{ 36, 3, "HCI_LE_Set_Extended_Advertising_Data"},
	{ 36, 4, "HCI_LE_Set_Extended_Scan_Response_Data"},
	{ 36, 5, "HCI_LE_Set_Extended_Advertising_Enable"},
	{ 36, 6, "HCI_LE_Read_Maximum_Advertising_Data_Length"},
	{ 36, 7, "HCI_LE_Read_Number_of_Supported_Advertising_Sets"},
	{ 37, 0, "HCI_LE_Remove_Advertising_Set"},
	{ 37, 1, "HCI_LE_Clear_Advertising_Sets"},
	{ 37, 2, "HCI_LE_Set_Periodic_Advertising_Parameters"},
	{ 37, 3, "HCI_LE_Set_Periodic_Advertising_Data"},
	{ 37, 4, "HCI_LE_Set_Periodic_Advertising_Enable"},
	{ 37, 5, "HCI_LE_Set_Extended_Scan_Parameters"},
	{ 37, 6, "HCI_LE_Set_Extended_Scan_Enable"},
	{ 37, 7, "HCI_LE_Extended_Create_Connection"},
	{ 38, 0, "HCI_LE_Periodic_Advertising_Create_Sync"},
	{ 38, 1, "HCI_LE_Periodic_Advertising_Create_Sync_Cancel"},
	{ 38, 2, "HCI_LE_Periodic_Advertising_Terminate_Sync"},
	{ 38, 3, "HCI_LE_Add_Device_To_Periodic_Advertiser_List"},
	{ 38, 4, "HCI_LE_Remove_Device_From_Periodic_Advertiser_List"},
	{ 38, 5, "HCI_LE_Clear_Periodic_Advertiser_List"},
	{ 38, 6, "HCI_LE_Read_Periodic_Advertiser_List_Size"},
	{ 38, 7, "HCI_LE_Read_Transmit_Power"},
	{ 39, 0, "HCI_LE_Read_RF_Path_Compensation"},
	{ 39, 1, "HCI_LE_Write_RF_Path_Compensation"},
	{ 39, 2, "HCI_LE_Set_Privacy_Mode"},
	{ 39, 3, "HCI_LE_Receiver_Test [v3]"},
	{ 39, 4, "HCI_LE_Transmitter_Test [v3]"},
	{ 39, 5, "HCI_LE_Set_Connectionless_CTE_Transmit_Parameters"},
	{ 39, 6, "HCI_LE_Set_Connectionless_CTE_Transmit_Enable"},
	{ 39, 7, "HCI_LE_Set_Connectionless_IQ_Sampling_Enable"},
	{ 40, 0, "HCI_LE_Set_Connection_CTE_Receive_Parameters"},
	{ 40, 1, "HCI_LE_Set_Connection_CTE_Transmit_Parameters"},
	{ 40, 2, "HCI_LE_Connection_CTE_Request_Enable"},
	{ 40, 3, "HCI_LE_Connection_CTE_Response_Enable"},
	{ 40, 4, "HCI_LE_Read_Antenna_Information"},
	{ 40, 5, "HCI_LE_Set_Periodic_Advertising_Receive_Enable"},
	{ 40, 6, "HCI_LE_Periodic_Advertising_Sync_Transfer"},
	{ 40, 7, "HCI_LE_Periodic_Advertising_Set_Info_Transfer"},
	{ 41, 0, "HCI_LE_Set_Periodic_Advertising_Sync_Transfer_Parameters"},
	{ 41, 1, "HCI_LE_Set_Default_Periodic_Advertising_Sync_Transfer_-Parameters"},
	{ 41, 2, "HCI_LE_Generate_DHKey [v2]"},
	{ 41, 3, "HCI_Read_Local_Simple_Pairing_Options"},
	{ 41, 4, "HCI_LE_Modify_Sleep_Clock_Accuracy"},
	{ 41, 5, "Reserved for future use"},
	{ 41, 6, "Reserved for future use"},
	{ 41, 7, "Reserved for future use"},
};
const char *
btcommandbitmask(uint8_t byte, uint8_t bit)
{
	struct bt_commandbitmask_str *bitmask;
	int i;
	if (byte >= nitems(bt_commandbitmask_strs)/8)
		return ("Reserved for future use");
	if (bit >= 8)
		return ("invalid command bitmask bit");
	for (i=byte*8; i < nitems(bt_commandbitmask_strs); i++) {
		bitmask = &bt_commandbitmask_strs[i];
		if (bitmask->byte == byte && bitmask->bit == bit)
			return (bitmask->desc);
		else if (bitmask->byte > byte)
			break;
	}
	return ("invalid command byte/bitmask");
}

struct bt_featurebitmask_str {
	uint8_t		 byte;
	uint8_t		 bit;
	char		*desc;
} bt_featurebitmask_strs[] = {
	{ 0, 0, "3 slot packets"},
	{ 0, 1, "5 slot packets"},
	{ 0, 2, "Encryption"},
	{ 0, 3, "Slot offset"},
	{ 0, 4, "Timing accuracy"},
	{ 0, 5, "Role switch"},
	{ 0, 6, "Hold mode"},
	{ 0, 7, "Sniff mode"},
	{ 1, 0, "Reserved"},
	{ 1, 1, "Power control requests"},
	{ 1, 2, "Channel quality driven data rate (CQDDR)"},
	{ 1, 3, "SCO link"},
	{ 1, 4, "HV2 packets"},
	{ 1, 5, "HV3 packets"},
	{ 1, 6, "μ-law log synchronous data"},
	{ 1, 7, "A-law log synchronous data"},
	{ 2, 0, "CVSD synchronous data"},
	{ 2, 1, "Paging parameter negotiation"},
	{ 2, 2, "Power control"},
	{ 2, 3, "Transparent synchronous data"},
	{ 2, 4, "Reserved for flow control lag(least significant bit)"},
	{ 2, 5, "Reserved for flow control lag(middle bit)"},
	{ 2, 6, "Reserved for flow control lag(most significant bit)"},
	{ 2, 7, "Broadcast Encryption"},
	{ 3, 0, "Reserved for future use"},
	{ 3, 1, "Enhanced Data Rate ACL 2 Mb/s mode"},
	{ 3, 2, "Enhanced Data Rate ACL 3 Mb/s mode"},
	{ 3, 3, "Enhanced inquiry scan (deprecated)"},
	{ 3, 4, "Interlaced inquiry scan"},
	{ 3, 5, "Interlaced page scan"},
	{ 3, 6, "RSSI with inquiry results"},
	{ 3, 7, "Extended SCO link (EV3 packets)"},
	{ 4, 0, "EV4 packets"},
	{ 4, 1, "EV5 packets"},
	{ 4, 2, "Reserved for future use"},
	{ 4, 3, "AFH capable slave"},
	{ 4, 4, "AFH classification slave"},
	{ 4, 5, "BR/EDR Not Supported"},
	{ 4, 6, "LE Supported (Controller)"},
	{ 4, 7, "3-slot Enhanced Data Rate ACL packets"},
	{ 5, 0, "5-slot Enhanced Data Rate ACL packets"},
	{ 5, 1, "Sniff subrating"},
	{ 5, 2, "Pause encryption"},
	{ 5, 3, "AFH capable master"},
	{ 5, 4, "AFH classification master"},
	{ 5, 5, "Enhanced Data Rate eSCO 2 Mb/s mode"},
	{ 5, 6, "Enhanced Data Rate eSCO 3 Mb/s mode"},
	{ 5, 7, "3-slot Enhanced Data Rate eSCO packets"},
	{ 6, 0, "Extended Inquiry Response"},
	{ 6, 1, "Simultaneous LE and BR/EDR to Same Device Capable (Controller)"},
	{ 6, 2, "Reserved for future use"},
	{ 6, 3, "Secure Simple Pairing (Controller Support)"},
	{ 6, 4, "Encapsulated PDU"},
	{ 6, 5, "Erroneous Data Reporting"},
	{ 6, 6, "Non-flushable Packet Boundary Flag"},
	{ 6, 7, "Reserved for future use"},
	{ 7, 0, "HCI_Link_Supervision_Timeout_Changed event"},
	{ 7, 1, "Variable Inquiry TX Power Level"},
	{ 7, 2, "Enhanced Power Control"},
	{ 7, 3, "Reserved for future use"},
	{ 7, 4, "Reserved for future use"},
	{ 7, 5, "Reserved for future use"},
	{ 7, 6, "Reserved for future use"},
	{ 7, 7, "Extended features"},
	{ 8, 0, "Secure Simple Pairing (Host Support)"},
	{ 8, 1, "LE Supported (Host)"},
	{ 8, 2, "Simultaneous LE and BR/EDR to Same Device Capable (Hosts)"},
	{ 8, 3, "Secure Connections (Host Support)"},
	{ 16, 0, "Connectionless Slave Broadcast – Master Operation"},
	{ 16, 1, "Connectionless Slave Broadcast – Slave Operation"},
	{ 16, 2, "Synchronization Train"},
	{ 16, 3, "Synchronization Scan"},
	{ 16, 4, "HCI_Inquiry_Response_Notification event"},
	{ 16, 5, "Generalized interlaced scan"},
	{ 16, 6, "Coarse Clock Adjustment"},
	{ 16, 7, "Reserved for future use"},
	{ 17, 0, "Secure Connections (Controller Support)"},
	{ 17, 1, "Ping"},
	{ 17, 2, "Slot Availability Mask"},
	{ 17, 3, "Train nudging"},
};
#define FEATUREBITMASK_MAX_BYTE 17
const char *
btfeaturebitmask(uint8_t byte, uint8_t bit)
{
	struct bt_featurebitmask_str *bitmask;
	int i;
	if (byte > FEATUREBITMASK_MAX_BYTE)
		return ("Reserved for future use");
	if (bit >= 8)
		return ("invalid command bitmask bit");
	for (i=0; i < nitems(bt_featurebitmask_strs); i++) {
		bitmask = &bt_featurebitmask_strs[i];
		if (bitmask->byte == byte && bitmask->bit == bit)
			return (bitmask->desc);
		else if (bitmask->byte > byte)
			break;
	}
	return ("Reserved for future use");
}
