.\"	$OpenBSD$
.\"
.\" Copyright (c) 2020 Fabien Romano <fabien@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt BLUETOOTH 4
.Os
.Sh NAME
.Nm bluetooth
.Nd introduction to Bluetooth support
.Sh SYNOPSIS
.Cd "bluetooth* at uhub?"
.Sh DESCRIPTION
.Ox
provides machine-independent bus support and drivers for Bluetooth (BT) devices.
.Pp
The
.Ox
.Nm
driver has four layers :
the bus (abstracted), the controller engine (HCI), the host, and the device layer.
.Sh SEE ALSO
.Xr bthci 9
.Sh HISTORY
The
.Nm
driver
appeared in
.Ox 6.8 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was written by
.An Fabien Romano Aq Mt fabien@openbsd.org .
